### ISSUE TITLE
Email sent twice for security notifications

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#1013]
Every time a SA is published, I get two emails about it. I've confirmed with several other people that they are seeing the same behavior. 

I had previously thought that maybe we were saving the published node twice, somehow, which triggered the second email. But today I published the SA using the bulk operation on the `admin/content` listing, so I know I didn't bumble the submit button.

I think we should look into our code for this to confirm we aren't triggering the send function twice.

**Comment by yorkshire-pudding** [comment]
I confirm that I get 2 emails for each security release.

**Comment by bugfolder** [comment]
We are indeed triggering the send function twice, on two consecutive cron calls 5 minutes apart.

Here's relevant dblog entries for the latest:

![image](https://github.com/backdrop-ops/backdropcms.org/assets/29214084/4ccb13b9-c834-432a-b7ee-06e8663a6259)

When an SA node is inserted or updated, we call `_borg_mailers_security_worker()`, which

* checks if we have sent mail for this node;
* if not, it creates a BackdropQueue item for the node;
* then records that we have sent mail for this node (which should prevent further duplicates of the queue item).

Since those three things happen quickly within the same function, it appears that only one queue item is getting created.

The queue item callback is `_borg_mailers_security_cron_send_email()`. This records when it starts and completes in the dblog, and you can see that it starts twice. Note that it takes longer than 5 minutes to complete, so a second cron call happens before the mailing is complete.

In `backdrop_cron_run()`, queued items are called like this:

```
  foreach ($queues as $queue_name => $info) {
    if (!empty($info['skip on cron'])) {
      // Do not run if queue wants to skip.
      continue;
    }
    $callback = $info['worker callback'];
    $end = time() + (isset($info['time']) ? $info['time'] : 15);
    $queue = BackdropQueue::get($queue_name);
    while (time() < $end && ($item = $queue->claimItem())) {
      try {
        call_user_func($callback, $item->data);
        $queue->deleteItem($item);
      }
      catch (Exception $e) {
        // In case of exception log it and leave the item in the queue
        // to be processed again later.
        watchdog_exception('cron', $e);
      }
    }
  }
```

So the item gets deleted after its callback is called, but if the callback takes longer than the interval between cron calls, the item will not have been deleted when the next cron call rolls around, and so the callback will happen twice. And this seems to be what is happening here.

So, there's a couple possible solutions.

The simplest would be to not call cron every five minutes. Since these jobs are taking about 6–7 minutes, it would be sufficient to space them out to every 10 minutes. (I seem to recall that there was a reason we wanted frequent cron calls, though; perhaps @jenlampton could comment on this?)

Another would be to modify the worker call to store a state variable when it starts that records that it has started for the specified node, and then it checks to see if it has already started on that node and won't run twice for the same node. That seems a bit kludgy, but it would be impervious to frequency of cron calling.

And a third would be to harden core queue processing logic against this situation, for example, to record in a queue item that it has started before calling its callback.

Thoughts?

**Comment by jenlampton** [comment]
> I seem to recall that there was a reason we wanted frequent cron calls,

There are a few reasons, but one is because we often schedule posts to go live at a certain time, and they can be up to cron-frequency late.  

I would prefer that we try to fix the bug than to add a work-around, but we can certainly increase the cron frequency the next time we have an SA if we don't have a fix ready by then :)

> then records that we have sent mail for this node (which should prevent further duplicates of the queue item).

Have we determined why this isn't working as intended? If the sent mail indicator was recorded during the first cron run, after the BackdropQueue item was created, then the second cron run should not be sending mail for that node again. 

Is it maybe, waiting for the BackdropQueue item to be completed, before recording the sent mail indicator? If so, that seems it could be the place to fix it.

**Comment by jenlampton** [comment]
> And a third would be to harden core queue processing logic against this situation, for example, to record in a queue item that it has started before calling its callback.

I like this idea. 🤔  There are some things that may need to be started every 5 minutes regardless of whether the first call has completed. I don't think it's safe to do this for all queue items. There would need to be a setting on the queue item that would allow it to opt-out of the double-duty protection (but I do think an opt-in by default would be smart).

**Comment by bugfolder** [comment]
> Have we determined why this isn't working as intended? If the sent-mail-indicator was recorded during the first cron run, after the BackdropQueue item was created, then the second cron run should not be sending mail for that node again.

It should not, but that's not what's happening. The sent-mail-indicator (`_borg_mailers_record_mail_sent()` and `_borg_mailers_check_if_already_sent()` ensure that only a single queue item is created, in function `_borg_mailers_security_worker()`:

```
function _borg_mailers_security_worker($node) {
  // Check if we have sent mail for this node already.
  $sent = _borg_mailers_check_if_already_sent($node->nid);

  if (!$sent) {
    if (($node->type == 'sa') && $node->status == 1) {
      $queue = BackdropQueue::get('borg_mailers_security_cron_send_email');
      $queue->createItem($node->nid);

      // Set a watchdog message and print a message for the user.
      backdrop_set_message(t('Mail is queued to be sent Backdrop CMS Security list subscribers on next cron run.'));

      // Record that the message has been queued to be sent.
      _borg_mailers_record_mail_sent($node->nid);
    }
  }
}
```

The problem is that the _same queue item_ is being called twice, because the queue item is not completed and deleted by the time that cron runs again.

So this is actually an issue with Backdrop core. _Any_ BackdropQueue item whose duration exceeds the cron-to-cron time interval will end up getting called twice (or more often, depending on how long it takes and how short cron-to-cron is). The security mailer situation just happens to be the first time we've explored this particular corner case.

**Comment by bugfolder** [comment]
>> Another would be to modify the worker call to store a state variable when it starts that records that it has started for the specified node, and then it checks to see if it has already started on that node and won't run twice for the same node.

> Isn't this exactly what the sent-mail-indicator is (and is intended to do)?

It's not what the sent-mail-indicator is (but perhaps it was what it was intended to do). Currently, the sent-mail-indicator indicates that a BackdropQueue item has been created, not that the mail has been sent.

But we could move those two calls `_borg_mailers_check_if_already_sent ` and `_borg_mailers_record_mail_sent ` a level deeper, into `_borg_mailers_security_cron_send_email()`, where I think it would serve the intended function.

**Comment by jenlampton** [comment]
That sounds good, let's try that first since it also sounds like not too much work.

**Comment by bugfolder** [comment]
I've made the changes (and tested it on a local site). @jenlampton, would you please take a look.

**Comment by jenlampton** [comment]
I still got 2 emails, but only 1 minute apart this time.  Did you test it
twice?

**Comment by bugfolder** [comment]
No, the two emails you got were from the live site, prior to the fix (I'd intended to do the test on my local site, but sent my SA to the live site by mistake).

**Comment by bugfolder** [comment]
Merged and tested (sending out a clearly marked dummy advisory). Only one copy received, so the fix worked. Leaving this closed.

**Comment by jenlampton** [comment]
Thank you!!
