### ISSUE TITLE
Scrollbar in the drawer

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#111]
Chrome 1440x90 resolution monitor settings. @wesruv 

![scroll](https://cloud.githubusercontent.com/assets/1042283/10109462/a6e3599a-638c-11e5-82ac-b4bf12f93f74.PNG)

**Comment by klonos** [comment]
1440x90?? 1440x**900** you mean?

**Comment by quicksketch** [comment]
I think this is intentional. We could implement some kind of JS scrolling solution, but those tend to be finicky and not compatible across all devices. On my computer with a smaller resolution (1280x800), there has always been a scrollbar.

**Comment by wesruv** [comment]
Yeah, I highly recommend keeping it as native scrolling behavior.

We do have quite a bit in that menu, I wouldn't be opposed to grouping more
or reworking it a bit, but if it doesn't quite fit in the screen, this
should be the expected behavior.

We could potentially group up the first three links in about, and group up
the module, theme and layouts party of the user guide. So they're one link
in the menu, but are small sub sections.

Would need to rework content a little too make a couple overview pages, but
it could help scannability on the nav and going l give us some
opportunities to describe some gestalt stuff about our extensions and how
we run the project.

**Comment by docwilmot** [comment]
> I wouldn't be opposed to grouping more or reworking it a bit

That was the point, thanks.

**Comment by docwilmot** [comment]
I still don't like this, but maybe just me. Could we consolidate links as proposed so the drawer doesnt need to scroll?

**Comment by jenlampton** [comment]
I did remove a few links from the handbook recently, not sure if this is still a problem at 1440x900, but we will not be able to always show all the links for everyone. At some point it's gotta scroll for someone :)

**Comment by jenlampton** [comment]
I like that idea. Closing (for now).
