### ISSUE TITLE
Make Drop the official Backdrop logo

### ISSUE THREAD

**Issue by sutibun** [backdrop-ops/backdropcms.org#114]
Eh... this might be controversial but can we have Drop the dragon as our official logo?

The boxy logo isn't terrible and I get [the meaning behind it](https://backdropcms.org/presskit) (it makes rational sense) but seems kinda generic.

![logo-challenge](https://cloud.githubusercontent.com/assets/14132746/10121418/79dd1650-64b0-11e5-85ff-7dd854693519.png)

I'll feel better standing behind a cute dragon than a box.

Drop is already a hit in shirt giveaways. People will better associate Backdrop with a dragon than a square. Even though I don't like Drupal's logo (it's really the face), I know if I see a water drop-like image, I immediately think of Drupal.

Likewise, when anyone sees a dragon-like image, they should think of Backdrop.

pls?

Guess issue #113 is related.

**Comment by quicksketch** [comment]
Hi @sutibun! So first of all some explanation as to why we have two representations in the first place:

- The logo is intended to be an unmodifiable constant. Although simple, it works in every possible size, color situation, and format.
- Drop (our mascot) on the other hand, is intended to be modified for any available purpose. He already comes in 2 poses, and we've hired an illustrator to expand that another 2 or 3 poses. It'd be exceedingly uncommon for any organization to pose their logo multiple different ways.

This arrangement is mirrored over in Drupal, where the official logo is actually the Drupal wordmark, see https://www.drupal.org/drupal-media-kit. Drupalicon is the "mascot", not the logo. Otherwise you wouldn't be seeing it used in every conceivable manner and variation for DrupalCamps and local user groups.

GitHub is a similar situation, where they have a logo (wordmark). But then they have a "mark" and "ocotcat": https://github.com/logos Although they say on that page not to modify Octocat on that page, in actual usage Octocat is GitHub's mascot. They modify it plenty and encourage others to do so as well. See the official repository of Octocats for example: https://octodex.github.com/

So in the same way, Backdrop has a "logo" (the box) and it has a mascot (Drop). The logo is an unmodifiable constant. The mascot you can do whatever you like with it. That doesn't mean that both concepts can't be extremely tied to the same brand. It gives us flexibility for when we want to be formal (logo) or fun (mascot).

**Comment by sutibun** [comment]
aah, didn't know that. 

So that's why Drupal has text on top of their website.

I just like the dragon and want to see more of him/her/it. Of course, that leads me to issue #113.

I'm satisfied then. Guess I'll close this.
