### ISSUE TITLE
[UX] Separate the links to download & link to view more info on a module/theme/layout

### ISSUE THREAD

**Issue by sutibun** [backdrop-ops/backdropcms.org#119]
It gets me every time.

Whenever I want to read more about a new project, I stop my mouse and think whether the link I am about to click is the right one.

![downinfo](https://cloud.githubusercontent.com/assets/14132746/10712956/c23336da-7a6f-11e5-863e-bfab3d27a578.png)

These links are too close to each other unnecessarily. Click one and you automatically trigger a download.The most likely scenario people will use is clicking the "more info" link and only then think of downloading once they've read about the project.

Anyway, I suggest we separate them out. Maybe moving the download link all the way to the right to avoid accidental clicks?

**Comment by jenlampton** [comment]
> The most likely scenario people will use is clicking the "more info" link and only then think of downloading once they've read about the project.

I'm not so sure about that, I think a lot of developers will be using this to get download links to their fav projects and won't go to the module page at all.  We should collect some stats on which link is clicked more before we jump to conclusions :)

> I suggest we separate them out. 

I agree with this, they are very close together and I often accidentally click the wrong one (for me, it's the more info link) too.

**Comment by jenlampton** [comment]
Bam. https://backdropcms.org/modules

**Comment by klonos** [comment]
Like! :+1:  Thanx.

**Comment by sutibun** [comment]
Like the new oval download buttons. Stands out from the boxy look of Bd's site.

> I'm not so sure about that, I think **a lot of developers** will be using this to get download links to their fav projects and won't go to the module page at all.

I don't doubt that there will be a handful of *experienced* developers who prefer the download link right away... the key word though is *experienced Bd developer*. To someone who knows Bd already, it's likely the module page is an unnecessary and prob burdensome step.

**But, remember who we are going after?** Users new to the Bd ecosystem. What are they likely to think when they come across this?

![module-download](https://cloud.githubusercontent.com/assets/14132746/12773705/c2ee916c-ca03-11e5-96f2-4aa42992de41.png)

From basic design (e.g. F pattern, shapes commanding attention) we can all deduce what will be the likely behavior: Eyes will focus on the download button. Someone new to Bd will likely think what they see is all there is to it, easily overlooking the "more info" link and thus missing possibly important info like "known issues"

![bd-issues](https://cloud.githubusercontent.com/assets/14132746/12774027/b88c6872-ca06-11e5-95a8-7fcf6ece9f8b.png)

On top of that, at least to me, it doesn't make sense that in the theme pages (and prob Layouts?) the main objective is "download" ...
 
![bd-themes](https://cloud.githubusercontent.com/assets/14132746/12773561/7fd37cea-ca02-11e5-8e3c-526142031696.png)

... because users will likely want to see how the theme looks followed by reading any theme requirements. Someone who prefers the download button first is a user who knows what they want. Experienced. New users will want to read up more on the project and then make a decision.

If you check out [Wordpress' plugin directory](https://wordpress.org/plugins/), you'll see each plugin providing a brief summary. However, the main objective is to get the user to check out the whole project page.

![wp](https://cloud.githubusercontent.com/assets/14132746/12774230/89f0d29e-ca08-11e5-9812-4dc15f87ba9e.png)

On [Joomla's extension directory](http://extensions.joomla.org/category/communication), you get a different style but same goal: push user to the project page.

![joomla](https://cloud.githubusercontent.com/assets/14132746/12774334/80ba8f84-ca09-11e5-91d2-62e84ab1d639.png)

On [Drupal's module directory](https://www.drupal.org/project/project_module), it's different in that they show substantial info followed by download links. It's not bad but, to me, the point of a directory is to promote browsing. Having long project info means lots of scrolling which discourages users.

![drupal-download](https://cloud.githubusercontent.com/assets/14132746/12774385/e745edde-ca09-11e5-9bc0-dd45ad6da10d.png)

Just imagine if the App store listings displayed everything like Drupal... eventually you'll feel overwhelmed and give up looking around. Too much unnecessary scrolling.

But, lets imagine for one moment that Drupal users are the main target of Bd. No new users. Well, even then, the download button won't be their first action. They'll want to check out the module page to see how different it is from the Drupal version and if they need to make any adjustments.

As is now, the pages looks nice but, IMO, not well designed.

> We should collect some stats on which link is clicked more before we jump to conclusions :)

With neither of us having hard data, we're **both** "jumping" to conclusions in our recommendations. (though I can make an argument that most designers don't get hung up on data as the end be all)

I tried.

I could def be wrong in my above POV and recommendation. My only "problem" is you're using your power as founder to jump over any arguments/discussions and basically push your conclusions, which discourages others from participating. Not a good for a community leader. I get that sometimes to get things done, decisions have to be made. But still...

**Comment by jenlampton** [comment]
> I could def be wrong in my above POV and recommendation. My only "problem" is you're using your power as founder to jump over any arguments/discussions and basically push your conclusions, which discourages others from participating. Not a good for a community leader.

Ouch. This issue was just to separate the two links (both spatially, and visually) which has been done. I achieved the goal stated here (and did so to the best of my abilities). 

in general my approach to solving design and UX problems is the same as with code. It's better to improve things a little bit at a time rather than doing nothing while bikeshedding what the "right" solution should be. I'm sorry if you think that I'm abusing my power.

I am no designer, and I certainly don't claim that what we have now "right" or the best it can be. All I know is that it's better than it was before.

> As is now, the pages looks nice but, IMO, not well designed.

That's because these pages aren't designed yet (which you might know if you read through the relevant issues, or participated in some of the design calls). We are using the design from the modules page on those other pages because having those pages exist on the site is better than not having them at all yet.

I would encourage you to take your feedback from above and put it into issues about the design of those pages, and not on this issue, which was to separate two links. Back to the point here...

> From basic design (e.g. F pattern, shapes commanding attention) we can all deduce what will be the likely behavior: Eyes will focus on the download button. Someone new to Bd will likely think what they see is all there is to it, easily overlooking the "more info" link and thus missing possibly important info like "known issues".

Would it help if we moved the more info link to the left and the download button on the right? What would be helpful are actionable suggestions, not your accusations and sexism.

**Comment by sutibun** [comment]
> Would it help if we moved the more info link to the left and the download button on the right? What would be helpful are actionable suggestions, not your accusations and sexism.

Not sure where you get the sexism. I personally think you're extremely talented and smart. Not only do you know programming (which I am no good at) but you have good design sensibilities. Something you don't find in your average developer, who tend to think too rigid and logical.

Maybe it's just me but you come off as so dismissive in your comments to the point I feel like I was silly to even suggest it.

**Comment by jenlampton** [comment]
I don't think we are talking about the issue anymore, please email me so we can work out whatever personal issues we are having. The issue queue is no place for our drama :) you can use info@backdropcms.org if you don't have my personal email and I will reply from my own email.

**Comment by klonos** [comment]
> in general my approach to solving design and UX problems is the same as with code. It's better to improve things a little bit at a time rather than doing nothing while bikeshedding what the "right" solution should be. I'm sorry if you think that I'm abusing my power.

I just left a related comment in https://github.com/backdrop-ops/backdropcms.org/issues/168#issuecomment-179083259. I really like the "get things done approach" @jenlampton is taking. It is best than not taking action IMO. If we decide there's a better way, we can always suggest changes and if approved, implement them.

:+1: for no dramas :smile:

**Comment by jenlampton** [comment]
Thanks @klonos. I was so proud of myself that we had actually started making progress on these issues, just to be shot down about not doing it right. Sorry @sutibun if I overreacted. I want to find out why you feel I'm a bad leader and overly dismissive (hopefully with some suggestions as to how to improve?) but let's take that offline. Please email me?

I didn't get any feedback on my idea of putting the more info link on the left and moving download to the right, but I moved it anyway. I think that might help the over-powering-ness of the download button @sutibun was worried about.  I also tried to change the visual weight of the more info link, since that was also part of the problem. Now the two are visually differentiated by rounded-corners vs square corners - I hope that's enough: https://backdropcms.org/modules

I am not a designer so I think this is the end of what I am able to improve without new designs to work from. These listing pages are definitely going to need another design review to clean up all the dates we've added, so we'll address link/button styles and positions then.

Closing issue again.

**Comment by sutibun** [comment]
Sorry, I tend to get home late. I'll email you in a few.
