### ISSUE TITLE
[SURVEY] How do you stay up to date with Drupal news and stuff?

### ISSUE THREAD

**Issue by sutibun** [backdrop-ops/backdropcms.org#138]
Trying to get a feel for the Drupal landscape. #126 So, I am hoping you can help me by answering two simple questions:
1. How do YOU specifically stay up to date with Drupal stuff?
   - Are there any specific sites, blogs, FB page, magazines, podcast, groups, forums, etc that you regularly go to?
2. What sites are popular with Drupal users? (you don't necessarily have to follow but are aware of)

Unfortunately, even though I've used Drupal, I was never that into it so I am sort of ignorant as to how Drupal users get their Drupal news. For me, I only followed the Lullabot blog (though it was at the bottom of my newsreader and I only read it once in a while)

**Comment by Gormartsen** [comment]
1. Mostly via social networks (FB, TW, Skype groups and different chats) and http://drupal.ru
2. Applicable only for Russian: http://habrahabr.ru/hub/drupal/  http://drupal.ru

**Comment by sutibun** [comment]
Ah...

> Mostly via social networks (FB, TW, Skype groups and different chats)...

That's a lil' general.... are there any ones in particular within each? I mean specifically are there any Facebook pages/groups, popular twitter accounts you follow, etc?

**Comment by Gormartsen** [comment]
> That's a lil' general.... are there any ones in particular within each? I mean specifically are there any Facebook pages/groups, popular twitter accounts you follow, etc?

On FB and TW I just follow other developers, no groups. 
So when I get to know about something via FG or TW - it is really buzzy all way around.

I am managing right now http://drupal.ru (with twitter https://twitter.com/drupalru ) and already do some adv for BD.

**Comment by Gormartsen** [comment]
> Also, would you say most Russians can understand basic English? i.e. bilingual

That's not a common case.

**Comment by sutibun** [comment]
Ah... that's good info. Thanks. When you have time, can you link to the developers you follow (or at least the major ones)

> That's not a common case.

Ah... kk... thought could go after English-speaking people and Russians at the same time. Never mind.

**Comment by klonos** [comment]
I can speak on behalf of the Greek audience (not only Drupal - in general) and say that most of us speak and understand English fairly. According to [this](https://en.wikipedia.org/wiki/List_of_countries_by_English-speaking_population) more than 50% of our population speaks English ...which is pretty reasonable if you consider that we are a country that relies on tourism for a great portion of our income (I believe almost 20% of our GDP) and that English is being taught in primary schools as a second language. It is also an official requirement in order to acquire a job in the public sector and an unofficial (but I'm pretty sure a de facto) requirement in the private sector too.

I personally do not have time in my life in general. My choice of information when it comes to Drupal is usually google (I can be considered socially impaired when it comes to having FB/twitter etc accounts). So for Backdrop for example, I check the first 3-4 pages of google search of "backdrop cms" for any result that is not marked as already visited (usually something that creates "noise" tends to bubble up the list).

Then, I know this may sound really geeky, but I am a big issue queue creep (can't you tell?). This is mainly because that way I am directly informed of any new known major/critical or just popular issues and get to know first-hand when new features are implemented. That way, once something is merged, I can go and test it and provide feedback (one of the things I love doing in Drupal/Backdrop).

Where reading text is not enough for me to grasp ideas/terminology/methodology, then video tutorials is my next stop. The list here is endless. Off of the top of my head, names that come to mind is Lullabot, Node1, Drupal DoJo, BuildAModule, Daily Dose of Drupal, Lynda etc.

I guess in fall out of the norm of the "social" reality of our times.

**Comment by sutibun** [comment]
> I can speak on behalf of the Greek audience (not only Drupal - in general) and say that most of us speak 

Ah

> Then, I know this may sound really geeky, but I am a big issue queue creep (can't you tell?)

With all those old Drupal issues you reference here, monkey kind of suspected. ^_^ So, guess you get information directly and revolve around the official website then.

> Lullabot, Node1, Drupal DoJo, BuildAModule, Daily Dose of Drupal, Lynda etc.

Sweet. Will check them out. Never heard most of them. Grazie!

**Comment by mikemccaffrey** [comment]
> How do YOU specifically stay up to date with Drupal stuff?

Pretty much all of the news I read about Drupal is what is aggregated into The Weekly Drop newsletter: http://www.theweeklydrop.com/

**Comment by sutibun** [comment]
Ah, grazie @mikemccaffrey So many places never heard. Will have much to look into when all is said and done ^^)

**Comment by serundeputy** [comment]
i think we've gathered what we can here ... closing.
re-open if necessary.
