### ISSUE TITLE
[SURVEY] What made you switch from Drupal to Bd?

### ISSUE THREAD

**Issue by sutibun** [backdrop-ops/backdropcms.org#140]
One last set of questions hope you can help me with.

1. Can you tell me the story of how you first discovered Drupal? **What were the top 3 things that made Drupal attractive enough for you to try it out?**
2. What were the **top 3 reasons why you switched to Backdrop instead of upgrading to Drupal 8** (or at least give Bd a chance as opposed to going to another CMS)?
3. Now that you've tried Bd, **why do you still stay with Bd?**

**Comment by Gormartsen** [comment]
1. It was more than 7 years ago... Hard to remember. I need system that was flexible and was providing CMS features.
2. I was doing performance tests and was really surprised with complexity and how Drupal 8 was heavy.
Later I tried to port one of my simple modules and it was really ... Painful . Instead of creating few functions... I had to create many files with classes with .. Few methods. I really don't like to use oop for simple things. 
Also I got strong feelings that developers doesnot care about small users and all this complexity will require big guns.
3. I am providing drupalhosting solution for my clients and BD is looking good to replace Drupal 7 in near future. 
It's almost the same API, easy to switch from d7, include many good features ( I explained it more in another survey :))

**Comment by sutibun** [comment]
Waaah.. These are the things the monkey doesn't know. Thanks Gomar

**Comment by klonos** [comment]
1. Long time ago for me to remember too. IIRC  I think that I was looking for a framework/CMS to build my own website. Could have been pure marketing that got my initial attention or even the challenge of "difficult to master but very powerful/flexible".

2. a) I am really frustrated and disappointed by the slow responsiveness in the issue queue in d.org (both core and contrib) b) I saw a DrupalCon intro of D8 by Dries and it seemed like watching Steve Jobs presenting another "Apple first" c) I have very limited time and have invested lots of it in learning D7 ...even started my first steps in php coding and module development. The turn Drupal was taking with D8 did not appeal to me at all ...the contrary.

3. For the community!!! :heart:

**Comment by biolithic** [comment]
1) I was a developer making my own CMS's for clients, then I found various
PHP MVC frameworks (Codeigniter, Cake, Zend? Can't remember) to make CMS's
for the clients, then I got a job working on a website for a mayoral
election and it was built on Drupal.  So I thought, ok, I don't have to
write or import user management and routing and security and all this stuff
all the time, I can just use Drupal to do it out of the box and worry about
other things of the website.

2) I was sort of co-leading a local Drupal meetup group where it seemed
like I was doing all the grunt work to "build the community", with no
corporate support.  We would have a night where the presentation was on,
for example, Rules, and the corporate audience would not come, saying, "I
can program module anyways, I do not need Rules."  So we would have a
writing your own modules night and the people would say, "We write a lot of
modules...but they're for our internal clients which we can't share.  So,
we can't present.  So we won't come.."  Other people just came to eat and
drink and say, "Yea, Drupal is cool".  So I kinda left Drupal to be a
mobile web app builder.  I came back to Drupal to try to get some
e-commerce type stuff for myself and clients but nobody cared.  It seemed
like all the modules were broken or in dev state with no documentation, and
I applied but couldn't become a maintainer or submit fixes (maybe I wasn't
working for Acquia or a big enough company?).  People at the meetups would
say, "I don't think Drupal is for that.  Drupal is for universities and
governments."  Also, I would try to fix something for D7 and people would
say, "No, all fixes must go towards D8.  Then, when that works and D8 is
released, then you can apply the fix to D7."  Well, this went on for a few
years but now stuff can be applied to D7 again which is nice.

 Finally, the client work I was getting on Drupal was fixing UI messes
like, "We tried installed Commerce Kickstart, Panels, Context, Display
Suite, writing a bunch of custom css and javascript, and making a bunch of
template files on our site to make a "magically easy" admin section for our
clients, and now something is screwed up and you have to fix it!"   So you
have a situation which any non-Drupal-architecture-expert is going to just
read some blog posts or search on d.o and build the site layout by
installing all the layout modules/distributions they think are cool, and
the site becomes really slow, buggy or a train-wreck, and then you have to
hire someone to start from scratch using only one pattern (for example,
ONLY Panels, or ONLY theme X + blocks, etc).  Otherwise, when you switch
themes or install new UI modules, the whole site becomes un-maintain-able
and glitchy.  So the right person, let's say David Snopek whom I respect as
a knowledgeable Drupal person, can set up Panopoly UI correctly and the
site will be maintainable.  Drupal is great!  But I've been pulled into
many projects where the client said, "The developer/team before us were
AWESOME php developers.  They can program anything anytime anywhere.
However, on our site, we tried to use Bean module or switch themes or do
something with the layout and the whole site went down!"  So, for a content
management system that you are going to hand off to someone else, you need
some way of limiting site layout options like the Layout module in BD so
you aren't in panic mode all the time.  For the well run Drupal shop, this
is not usually a problem.  For the client, making a Drupal site responsive,
switching a look/theme, or upgrading a version can be more a problem in
Drupal than other current tech if you didn't have a great company behind it
to start and I think Bd solves these issues.

3) As a mainly front-end developer, I have to keep up with Angular and
React and Riot and Jquery-or-ES6 and Sass and PostCSS and Flexbox and
CSS-Grid and Handlebars and Polymer/Web Components and Node and HTML5 and
Cordova and all the things.  I might not get to becoming the world's
greatest Symfony developer this year in addition to them.   There already
exists the world's greatest Symfony developers -- they can be in charge of
Drupal.   I just need a CMS that's easy for clients to use and I've already
gone through Drupalize.me, Buildamodule, books/reading core code, NodeOne,
Camps, Cons and the all that jazz in a previous life.  Also, because I am
struggling with some health issues now, I don't have 24 hours a day to
learn things anymore.  I think smaller builds are more maintainable in the
long run for me.  If I was working on the Australian government website or
the United Nations website I think I would use Drupal8, but I'm not in
those positions.  I just worked on a Bd site where I made a View locally
and pushed the json config to Git and it worked!  That was pretty cool and
not time consuming.

**Comment by Gormartsen** [comment]
@biolithic Thats sad story! Get better. Actually this respond can help to build BD development process the way to avoid repeating the same situation.

**Comment by kreynen** [comment]
@biolithic That attitude towards Drupal meetups is not unique to your meetup and is also seen in camp attendance... though camps probably benefit from shops who present there to generate interest from clients and get to present at DrupalCon.  I think one factor that contributes to this is the shift in how much of someone's job/life Drupal already dominates.  When I got involved in Drupal, running a CMS for a college made up 25% of my job at most.  Very few people were full time Drupal developers abck then.   It was really enjoyable to spend an evening or weekend talking with other people using Drupal.  Many of them had backgrounds and philosophies about sharing code that were similar to mine.  Most were well informed about Drupal and know of (in not know) each other.  Many of us had been working in commercial system X, but thought there could be a better way both to accomplish tasks and earn a living.  The community was primarily young, idealistic developers.  

That is no longer the case.  When I go to Drupal meetups now, I can almost guarantee that a few things will happen...

* Someone will be there pitching their startup that has nothing to do with Drupal, but they are their "just to learn".  
* Someone will ask about migrating content between dev and prod
* Someone will offer me a job or project for 50% (and often MUCH less) than the market rate... "pstt... would you be willing to build out my idea for equity?"
* Someone will ask me to look at something that's wrong on a site without a dev or test instance on a $5/month hosting hotel

I have been working in Drupal full time for years... and I am much, much older.  When given a choice of what to do on the weekend or an evening, I'm now going to choose to spend it with my wife and kids.  I can also justify attending a technology related event during the week or do something with just my team (which is now as large as many meetups)... and I can do these as work.  

Backdrop's community reminds me of the early days of Drupal (which I really like!).  Unfortunately I'm not sure any project can be successful and inclusive while "avoid the repeating the same situation",but I'm happy to be proven wrong!

Is there any interest in a [SURVEY] What prevented you from switching from Drupal to Bd?

**Comment by sutibun** [comment]
> ... or even the challenge of "difficult to master but very powerful/flexible".

that also pulled the monkey in: the challenge!

> I am really frustrated and disappointed by the slow responsiveness in the issue queue in d.org (both core and contrib)

@klonos out of personal curiosity, why do you think it's slow?

> Also, I would try to fix something for D7 and people would say, "No, all fixes must go towards D8.  Then, when that works and D8 is released, then you can apply the fix to D7."

@biolithic monkey don't get it. Why would they stop your D7 fixes just because of D8. Aren't they two different systems/code?

> Is there any interest in a [SURVEY] What prevented you from switching from Drupal to Bd?

@kreynen go for it. Make it question 4. though would help if you could answer questions 1-3 if it applies as well.

Btw, you guys are helping me a lot! The more people answer, the better. Thanks everybody.

**Comment by klonos** [comment]
> ...out of personal curiosity, why do you think it's slow?

> ...monkey don't get it. Why would they stop your D7 fixes just because of D8. Aren't they two different systems/code?

I do not *think* it's slow. I *know* it is ...I have personally experienced it countless times. Issues that are really important to be sorted or features that have been tested and proven to be working never get merged. ...alright, "never" is a very hard word, but in my opinion 2+ years qualifies as "never" (and when it gets close to 4-5 years it qualifies as "never-ever"). The examples I have of such cases in the d.org issue queue are endless.

The [policy](https://www.drupal.org/core/backport-policy) to *fist* fix things in D8 (or more precisely D-next) and then merge in D7 (D-current) pisses me off:

> All proposed changes to Drupal core should be posted against the current development version (currently Drupal 8). This includes issues that were originally opened against previous versions - even if the original target was Drupal 6 or Drupal 7, once 8.x development starts, this is the target version for every change.

...especially in the early days of D8 development where things had not settled on which direction it would take etc. Endless discussions of whether things should be done or not and then how they should be done while the working fix/patch for D7 was lingering for years with people "pushing" for it to be merged ...in vain. Uhhh!

Hope this explains things a bit better.

**Comment by klonos** [comment]
I have not read the policy page for some time and it seems to have been updated. This bit gave me a good laugh:

> **Why do we do it like this?**

> Applying fixes to 8.x and backporting them, ensures that when 8.0 is released, it will have all the bug fixes that have made it into 7.x (and 6.x).

**Comment by klonos** [comment]
...what this translates to in reality is: "we ensure that things will not get fixed in D7 or D6 before D8 is released ...in like 5-6 years"

[shakes head]

**Comment by klonos** [comment]
...and it keeps going:

> - Patch reviewers generally will not check the issue queues of the current stable release, ...

...REALLY??? ...that's a good support practice! Well done!!

> - Core committers will not commit patches to the 'wrong' version, ...

"Wrong version"??? ...for who?? Makes you wonder who "we" is in the "Why do we do it like this?" ...it's supposed to be the community.

**Comment by sutibun** [comment]
> I have personally experienced it countless times. Issues that are really important to be sorted or features that have been tested and proven to be working never get merged... but in my opinion 2+ years qualifies as "never" (and when it gets close to 4-5 years it qualifies as "never-ever")

Waaah..

> The policy to fist fix things in D8 (or more precisely D-next) and then merge in D7 (D-current) pisses me off... .that's a good support practice! Well done!!

That's looney. 

Now wonder what made you even stick around 4+ years. Prob community?

**Comment by klonos** [comment]
> Now wonder what made you even stick around 4+ years.

It was stubbornness/persistence mainly. Plus I had invested a lot of my almost non-existent spare time learning Drupal 6/7. I didn't want that to go to waste.

It was also practicality. I did have to follow like a million issues in the queue and maintain a pretty big collection of patches that I had to re-apply every time I'd upgrade a site, but at the end of the day I got my job done. If I had no time, I would simply not attempt any upgrade.

Then it was also denial. I believed that the community would find a way to self-correct itself. I just refused to give up. ...wait that is stubbornness again :smile: 

The community is great! :heart:

**Comment by quicksketch** [comment]
Thanks for the great question @sutibun. :smile:

`#1`: Like others I'd been building my own custom CMS or piling together 3-4 different projects together to make a complete website. For my undergraduate research final, I evaluated Mambo, Drupal, and Plone. I thought Drupal was the best system at the time, and I could run it on cheap shared hosting (all a student could really afford). I built 4 sites during my evaluation, including my blog and a site for a local art association.

`#2`:
- This one comment in one issue: https://www.drupal.org/node/1890502#comment-6999042. I'd spent almost a year lobbying for, writing, and updating the CKEditor integration for Drupal 8. After that essential rewrite in a single comment, I basically found that that I didn't really understand Drupal any more. It got a lot worse in the next couple of months. The change was too great for me to overcome. Ultimately, I decided it was too hard and I'd had enough of the drastic changes between versions.
- The Drupal decision making process has often irked me. I think the community is great overall, but the lack of authority drove me crazy. If webchick had, and could exercise the authority to veto what she thought were bad ideas, I'd probably still be doing Drupal. But as it was, either loud, bad ideas were often implemented or nothing was implemented at all. Burnout was a constant issue for me.
- Drupal 8 broke from the existing principles of the Drupal project. I never liked the [backwards-compatibility stance](https://www.drupal.org/node/2613652) in the first place, but it wasn't until mid-betas (about a year ago) that the upgrade path and the philosophy of maintaining users' data was abandoned entirely. Drupal went from hellish upgrades to impossible upgrades.
- And lastly, I think that our crazy little community might actually make this work. We're comparatively very small, but I think we're a lot more effective. Less frustration and bureaucracy (hopefully) will let us do more with less. I also like the small community feel, which has been long since been dominated within Drupal by the behemoth companies. I'll never forget the amount of betrayal I felt when every square foot of DrupalCon London's venue was plastered with Acquia logos. That DrupalCon I felt the community and software that was *ours together* was suddenly *owned* by someone else. There's been a lot of marketing by Acquia reduce that sentiment, but after having been in Drupal for nearly a decade, I can't see it any other way.

`#3`: Yes. :wink:

Hopefully we've done a fair job of letting people know what they're getting into with Backdrop. Be sure that you agree with our https://backdropcms.org/philosophy and https://backdropcms.org/leadership. I'd hate to have the same thing happen to our community members who thought they were getting into one thing but found out a decade later that they didn't agree with the basic principles of the project.

**Comment by sutibun** [comment]
> For my undergraduate research final, I evaluated Mambo, Drupal, and Plone. **I thought Drupal was the best system at the time**, and I could run it on cheap shared hosting (all a student could really afford)

Why did you think it was the best system at the time?

> But as it was, either loud, bad ideas were often implemented or nothing was implemented at all.

What are the biggest examples of bad ideas?

> Be sure that you agree with our https://backdropcms.org/philosophy and https://backdropcms.org/leadership.

Like any one ever reads the fine print ( ^\_-)

**Comment by Gormartsen** [comment]
> Like any one ever reads the fine print ( ^_-)


@sutibun Actually I read and it was a part of making a decision to check it out.

**Comment by sutibun** [comment]
which begs the question: why isn't it more prominent?

**Comment by Gormartsen** [comment]
what do you mean by "it" ?)

**Comment by sutibun** [comment]
ah... the links to the philosophy & leadership page. (they also convinced the monkey)

**Comment by sutibun** [comment]
hmm... well, maybe we don't need a link.

> Actually I read and it was a part of making a decision to check it out.

@Gormartsen btw, was there anything in the leadership + philosophy page that resonated more than anything else?

**Comment by quicksketch** [comment]
Let's close this issue up after no new comments have been posted for a while. Thanks @sutibun for starting and facilitating such a great discussion. :+1:

**Comment by klonos** [comment]
Speaking of the monkey... have not seen him around the queue. Kinda miss your rather lengthy posts @sutibun ...I think they were the only ones competing with mine :smile:.
