### ISSUE TITLE
Add a project application form

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#155]
In response to https://github.com/backdrop-ops/contrib/issues/122#issuecomment-168800744

The process of application appears quite standardized and should lend itself to a webform with fields for the usual questions, followed by an "I accept" checkbox.

```
To contribute a module, we ask that you put the module you've ported or written up
in your personal GitHub account so that we can review it. 
It should be fully ported to Backdrop without using the 
Drupal compatibility mode setting in settings.php.

We require that at minimum, the following steps have been done:

- Include a LICENSE.txt file that indicates the code is GPL v2. You can use this copy.
- Include a README.md file that includes license and maintainer information. 
You can use this example.
- Maintain the Git history from Drupal 7. See this article.

Once the module has been reviewed, we can add you to the Backdrop Contrib group, 
and you can then transfer the module into http://github.com/backdrop-contrib. 

Please add your GitHub username

Please add other info...

... More stuff...

[  ] I accept the agreement

```

Would help ease the workload of @quicksketch and @jenlampton as the details could be delegated, and final approval granted after someone else makes sure the boxes are ticked.

**Comment by serundeputy** [comment]
i like this idea;  +1;

**Comment by jenlampton** [comment]
I'm not sure having a webform on the website makes it easier on @quicksketch or myself. The end result is that someone on GitHub needs to be added to a group on @GitHub, so having the applications on GitHub I think makes the most sense.

If the point is to make it easier on contributors then perhaps this is a good idea? But they will also need to be familiar with GitHub in order to contribute, so maybe not?

To make things faster / easier, maybe we just promote a few other people to be watchers of the applications and admins of the contrib group?

**Comment by docwilmot** [comment]
https://github.com/backdrop-ops/backdropcms.org/issues/155 is more recent and has more comments.

**Comment by oadaeh** [comment]
@docwilmot this is #155. Did you mean a different issue?

**Comment by docwilmot** [comment]
I meant https://github.com/backdrop-ops/backdropcms.org/issues/517, sorry
