### ISSUE TITLE
Automatic demo site for every CONTRIB module/theme/layout (a.k.a simplytest.me clone).

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#172]
It would be fantastic if we could set up an automatic demo of each project. It seems with CMI now this shouldn't be too hard to facilitate. If we were to add a /demo/ folder into the module (or into the config directory within?) we could pull in the project + initial demo config, along with perhaps a URL for viewing, and BAM create a demo site!

**Comment by docwilmot** [comment]
Or maybe a [Simplytest.me](https://simplytest.me/) clone? Don't know how that works though.

**Comment by Gormartsen** [comment]
I like this idea.

**Comment by klonos** [comment]
> Or maybe a Simplytest.me clone?

I thought I have already filed an issue about this already. Simplytest.me has a project on d.org (no code though :disappointed:): https://www.drupal.org/project/simplytest

**Comment by gifad** [comment]
@klonos : 
>  (no code though :disappointed:)

just [Browse code repository](http://drupalcode.org/project/simplytest.git) :smiley:

**Comment by quicksketch** [comment]
This was implemented in https://github.com/backdrop-ops/backdropcms.org/issues/5.

**Comment by klonos** [comment]
...not for contrib it was not. Not AFAICT at least: https://github.com/backdrop-contrib/google_fonts/pull/5

**Comment by klonos** [comment]
Just to clarify, this feature request here is in order to be able to have sandboxes for PRs against **contrib** projects that fire up a 1.x backdrop core sandbox **with** the respective contrib project already installed (extracted) under `/modules` or `/themes` or `/layouts` folder (depending on project type) **and already enabled**.

**Comment by klonos** [comment]
@Gormartsen no pressure 😛

**Comment by klonos** [comment]
I am not sure how relevant this is now, with the tugboat demo at https://backdropcms.org/demo/create ...we just need to solve #556 of course.

**Comment by stpaultim** [comment]
It would seem to me that this is a generic problem / issue to address and that tugboat is one possible solution. If we are committed to Tugboat as the best solution to this problem, then we could probably close this issue in favor of #556. Although, the intent of this issue seems to be a unique URL/path that could be used to demo every theme/module. The tugboat issue is to allow users to create a sandbox and then install any module/theme through the UI. This is not the same, but I think it might be a reasonable alternative.

**Comment by BWPanda** [comment]
I'm not sure this feature request is worth doing...

1. Where would we host a seperate, running website for every single contrib module? That's a lot of resources!
2. What about situations where you want to test one contrib module alongside another one? This could be because they compliment each other, or because you're trying to compare similar modules to see which best fits your needs.

I sugest instead that we recommend people spin up a demo sandbox where they can install whatever contrib modules, themes, or layouts they want. They can install as many projects in the one site as they need, and sandboxes are automatically cleaned up after 24 hours so there's no need to worry about resources. With all this now possible because https://github.com/backdrop-ops/backdropcms.org/issues/556 was fixed, I'm going to go ahead and close this issue as 'won't fix'.

Anyone should feel free to re-open if they feel strongly against this decision or would like to promote further discussion.
