### ISSUE TITLE
Add a link for login / register

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#182]
So not only the Backdrop & Drupal-savvy can figure it out.

**Comment by klonos** [comment]
:+1:

**Comment by serundeputy** [comment]
Here are two possibilities:

top right option:
![screen shot 2016-03-18 at 8 20 05 pm](https://cloud.githubusercontent.com/assets/6763671/13895232/5a54439c-ed47-11e5-93f8-9bbb5fcae9aa.png)

under logo in the left drawer nav:
![screen shot 2016-03-18 at 7 30 44 pm](https://cloud.githubusercontent.com/assets/6763671/13895233/5e8a758a-ed47-11e5-9e04-13661795ceb9.png)

**Comment by jenlampton** [comment]
I like it in the left sidebar :) @dariusgarza what do you think?

**Comment by dariusgarza** [comment]
Well...this is a bit of a table flip, but that logo might not be sustainable longterm 
![image](https://cloud.githubusercontent.com/assets/7042667/13895642/1e9b214a-ed33-11e5-9246-4f0151de2112.png)

**Comment by jenlampton** [comment]
I really like the idea of putting the login block in the drawer! Can we do that even without the logo-table-flip? :)

**Comment by dariusgarza** [comment]
I would still put the login/register links in the same area as the others. When its next to the logo, it sorta distorts the branding. And i just realized that its kinda weird to put the triangles next to links that don't have a drawer functionality ;)

**Comment by docwilmot** [comment]
If we bundled "modules", "themes" and "layouts" into their one drawer there'd be more room.

**Comment by klonos** [comment]
HMM, I'm torn. When the user logs in, the "log out" link is on the admin bar at the top-right corner (by the way, do we actually need both the "log out" link in the admin bar + the "log out" menu item in the sidebar?):

![backdropcms org-log_out_link_and_menu_item](https://cloud.githubusercontent.com/assets/2423362/13895626/bd9988fe-edc9-11e5-9421-78923eac6dde.png)

So, for consistency, I'd say one of the things below:

- have the "log in / register" links at the top-right where the "log out" link is in the admin bar. In this case, remove the "log out" menu item from the sidebar. Consistency++
- have the "log in / register" links in the sidebar. In this case, perhaps remove the "log out" link from the admin bar (?).

I really like @dariusgarza's design where the logo gets smaller and the "backdrop" word next to it in general, because it saves us vertical space on the sidebar. :+1: 

I also like the login form in the drawer. :+1: for that too, but what about mobile? (#197)

**Comment by jenlampton** [comment]
@klonos you can only see the admin bar because you are an admin. Most user's won't get that - you are special. 

I have added the login/register and logout links at the bottom of the sidebar, and @dariusgarza I fixed the arrow so it only shows up on items with a drawer. Right now Handbook is the only one with a drawer, but hopefully we'll add a drawer for login/register soon, and then it can get arrow too :)

**Comment by jenlampton** [comment]
I created this issue for the drawer: https://github.com/backdrop-ops/backdropcms.org/issues/209
