### ISSUE TITLE
Do we regularly update the project info (project node body) and if so, how often do we do it?

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#195]
As per issue title. Do we update the project node body in b.org with every new release of a project in GitHub? If so, it kinda makes sense because we want the info to be up to date in the actual project package downloaded too, but still doesn't that mean that minor corrections in the README *require* a new release? Hmm.

**Comment by Gormartsen** [comment]
Hi @klonos.

Yes it is.

Right now I am working on github integration for backdropcms.org

So what we can do is when we receive push event and if read me listed as updated or uploaded - we can act! For example pull new read me and update node.

**Comment by quicksketch** [comment]
> Do we regularly update the project info (project node body) and if so, how often do we do it?

We actually update the project info on *every commit*. So no new release is necessary to update the description on BackdropCMS.org. If it's on the landing page of a project when you visit it, the same description should be on BackdropCMS.org.

Though it's important to remember that the *default branch* is important here. If you have multiple branches, only the default branch will be used for its README.md. That's no surprise really because it's the same thing you'd see if you visited the project on GitHub without selecting an alternative branch.

**Comment by klonos** [comment]
Makes perfect sense. Thank you both for taking the time to explain.

**Comment by Gormartsen** [comment]
Just for the record. In current project.module version it's here: https://github.com/backdrop-contrib/project/blob/1.x-1.x/project_github/project_github.pages.inc#L574
