### ISSUE TITLE
Need to consider documentation

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#26]
Working on change records for layouts.module, it occured to me that there is a blur between change records and proper documentation for new stuff. Layouts in particular needs more than a "what changed", we need a whole lecture series (not really).
And when new users (non-ex-Drupalers) show up and need info about general stuff (how to...) we shouldnt be pointing them to Drupal.org?!
But we don't have a place for that yet do we?

**Comment by BWPanda** [comment]
I like the idea of contrib modules maintaining their own documentation. Whatever system we end up using for listing all contrib modules on BackdropCMS.org, we can add a 'Documentation' link to the module's GH Wiki page.

As for core documentation, I like the idea of having all documentation in the one place, rather than API documentation separate to how-to/tutorial-style documentation. I think https://github.com/backdrop-ops/api.backdropcms.org/issues/3 is the thing to do (adding documentation to API.BackdropCMS.org), making sure that we keep the structure simple and easy to find/navigate.

**Comment by BWPanda** [comment]
As per https://github.com/backdrop/backdrop-issues/issues/494#issuecomment-68510168, a page should be created (in amongst the how-to-write-a-module section) listing the recommended module 'packages' (again, I think this should go on the API site).

**Comment by jenlampton** [comment]
Sounds good to me. I started stubbing out a book for "Developer documentation" on the API site: https://api.backdropcms.org/documentation.

**Comment by docwilmot** [comment]
I'm on this. See the themes page https://api.backdropcms.org/node/28587
I'd like to suggest cosmetic improvements with the API site theme please:
* add a font-weight 500 to `<h2>` tags
* add a 2em margin-bottom to `<code>` blocks
* remove the border on `<code>`blocks and change the background to #F7F7F7 (same as GH). Currently code blocks are a bit harsh.
* I am suggesting a callout block like on this page http://symfony.com/doc/current/book/forms.html (the styled block with the pen icon) to call out important D7/BD differences. I used `<blockquote class="d7diff">`. If you like this idea, could you style with a `#eee` background and a 20px 20px 5px 50px padding, and remove the left border. If you have time for an icon, do that too, but not urgent.

Thanks

**Comment by jenlampton** [comment]
These are great suggestions, will try to get to them asap!

**Comment by quicksketch** [comment]
I think our current status on this is complete. We've started aggregating all developer documentation (both API-generated and node-based) at api.backdropcms.org. Let's make new issues for changes we'd like, and put them in the api.backdropcms.org queue: https://github.com/backdrop-ops/api.backdropcms.org/issues
