### ISSUE TITLE
No proper release files created (only source code .zip and .tar.gz)

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#264]
Noticed this lately with the latest contrib project releases (previous to last releases have a "download [project_name] [release_version] zip" link):

https://github.com/backdrop-contrib/field_permissions/releases/
https://github.com/backdrop-contrib/b4_radix_full/releases
https://github.com/backdrop-contrib/fixteaserlinks/releases

Seems that the packaging script is not running. If people download the source packages, the projects should still work fine, but they will have no version number in their .info files.

**Comment by klonos** [comment]
...the respective download link on the backdropcms.org side (in each release node) points to https://api.github.com/repos/backdrop-contrib/[project_name]/zipball/[release_tag] and the file actually downloaded is `backdrop-contrib-[project_name]-[release_tag]-0-[last_commit_sha].zip`. When extracted, the contents of the file are extracted to a folder in the form of `backdrop-contrib-[project_name]-[last_commit_sha]`.

**Comment by Gormartsen** [comment]
@klonos sounds like it project module does not work properly.

@quicksketch can you check log records on backdropcms.org ?
Sounds like some bug with payload.

**Comment by Gormartsen** [comment]
Latest module that was properly processed is Parsedown filter  that posted on Jun-5-2016.

**Comment by Gormartsen** [comment]
@klonos There is some updates happening with backdropcms.org (at least changes in backdrop-ops/backdropcms.org repo happen) Probably it does not connected.

@jenlampton I know that settings.php is not posted in repo for security reason.
@quicksketch  set up some variables for githubapi via settings.php.

Maybe they get removed after update by mistake. It is my best guess why it is not working properly now.

**Comment by klonos** [comment]
Logs:

php warning: `Warning: ZipArchive::extractTo(): Invalid or unitialized Zip object in _project_github_create_package() (line 204 of /home/backdrop/repo/www/modules/contrib/project/project_github/project_github.pages.inc).`

php warning: `Warning: ZipArchive::close(): Invalid or unitialized Zip object in _project_github_create_package() (line 205 of /home/backdrop/repo/www/modules/contrib/project/project_github/project_github.pages.inc).`

php warning: `Warning: file_get_contents(/tmp/project_pkg_ZZDPop/fixteaserlinks.zip): failed to open stream: No such file or directory in _project_github_create_package() (line 259 of /home/backdrop/repo/www/modules/contrib/project/project_github/project_github.pages.inc).`

php info: `Successfully created release for fixteaserlinks 1.x-1.0.0 and pushed the package to GitHub.`

php info: `Created project_release for Fix Teaser Links 1.x-1.0.0.`

Hope these help.

**Comment by Gormartsen** [comment]
@klonos tnx!
Sounds like access_token from `settings_get('project_github_access_token')` is not valid or empty

**Comment by Gormartsen** [comment]
@klonos if you do have access to backdropcms.org, check settings.php for project_github_access_token value.

If it is here, then either token get expired or user backdrop-ci does not have access to backdrop-contrib organization.

**Comment by klonos** [comment]
@Gormartsen I have admin role in the website, but no FTP access. Sorry, you'll have to wait for either @jenlampton or @quicksketch I'm afraid.

**Comment by Gormartsen** [comment]
@klonos Got it!

**Comment by jenlampton** [comment]
Can check in 1/2 hr or so.

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by jenlampton** [comment]
@Gormartsen the settings.php file still contains 'gitlc_webhook_api_token`. Any other ideas?

**Comment by Gormartsen** [comment]
Disk space? Is it possible that there is no space?
Is there extra notices in error log maybe?

Regards,
Gor Martsen
@gormartsen

**Comment by quicksketch** [comment]
The section of code that has the problem is this bit:

```php
  // Copy the file down locally.
  $result = backdrop_http_request($source_zip_url, array(
    'headers' => array(
      'Authorization' => 'token ' . $access_token,
    ),
  ));
  if ($result->code == 200) {
    file_put_contents($directory . '/original.zip', $result->data);
  }
  $archive = new ZipArchive();
  $archive->open($directory . '/original.zip'); // <- Line 204 where we get the first Zip error.
  $archive->extractTo($directory);
  $archive->close();
```

I think what's happening is that we're trying to download the original zip, but it's failing. We should be throwing an error or something there if the HTTP transfer fails, but instead we try to continue anyway. It's not disk space usage, we're only at 8%. My guess is that the GitHub package isn't ready at the time that we do the HTTP request. I'll look into it.

**Comment by quicksketch** [comment]
I re-sent the GitHub API request for the recent release of Media Element: https://github.com/backdrop-contrib/mediaelement/releases/tag/1.x-1.2.0. This time it ran perfectly and created the missing release zip file. So this seems to support my theory that GitHub just doesn't have the zip file ready yet at the time the web hook fires, because re-sending the exact same payload works if you run it again later.

**Comment by quicksketch** [comment]
Okay this is getting a little more weird. I tried re-sending the API request from GitHub for FileField Sources (https://github.com/backdrop-contrib/filefield_sources/releases/tag/1.x-1.0.0, great to see that ported BTW!) and it *failed the first time*. It gave the same ZipArchive errors. But then I sent the request again and it worked the second time. Very strange! I'll add extra logging into the module to see why it is failing to get the ZIP file from GitHub.

**Comment by Gormartsen** [comment]
It is strange. It would be good to have extra info. Like error code and raw github answer

**Comment by quicksketch** [comment]
Ugh, sorry about all the noise with my commits. This is a weird problem but I think I have the cause.

*Every* time I send a package request, it fails the *first* time. If I resend the same packaging request a second time, it works 100% of the time.

Comparing the returned HTTP responses from GitHub, the only difference is the first time we have a "transfer-encoding" header, and the second time we get a "content-length" instead:

First request response from GitHub when downloading the ZIP file:
```
    [protocol] => HTTP/1.1
    [status_message] => OK
    [headers] => Array
        (
            [transfer-encoding] => chunked
            [access-control-allow-origin] => https://render.githubusercontent.com
            [content-security-policy] => default-src 'none'; style-src 'unsafe-inline'
            [strict-transport-security] => max-age=31536000
            [vary] => Authorization,Accept-Encoding
            [x-content-type-options] => nosniff
            [x-frame-options] => deny
            [x-xss-protection] => 1; mode=block
            [etag] => "117214b5d28184631cb8e547ec8e7a09d179c46a"
            [content-type] => application/zip
            [content-disposition] => attachment; filename=backdrop-contrib-juiced_up_layouts-1.x-1.1.0-0-g117214b.zip
            [x-geo-block-list] => 
            [date] => Sun, 19 Jun 2016 23:46:41 GMT
            [x-github-request-id] => 17EF0A05:0417:1A4ACD:57672EE1
            [connection] => close
        )
```

Second request response from GitHub when downloading the ZIP file:
```
    [protocol] => HTTP/1.1
    [status_message] => OK
    [headers] => Array
        (
            [content-length] => 110492
            [access-control-allow-origin] => https://render.githubusercontent.com
            [content-security-policy] => default-src 'none'; style-src 'unsafe-inline'
            [strict-transport-security] => max-age=31536000
            [vary] => Authorization,Accept-Encoding
            [x-content-type-options] => nosniff
            [x-frame-options] => deny
            [x-xss-protection] => 1; mode=block
            [etag] => "117214b5d28184631cb8e547ec8e7a09d179c46a"
            [content-type] => application/zip
            [content-disposition] => attachment; filename=backdrop-contrib-juiced_up_layouts-1.x-1.1.0-0-g117214b.zip
            [x-geo-block-list] => 
            [date] => Sun, 19 Jun 2016 23:48:44 GMT
            [x-github-request-id] => 17EF0A05:0418:FBB2B:57672F5C
            [connection] => close
        )
```

Googling around, it looks like we hit a bug in Backdrop/Drupal: https://www.drupal.org/node/106506

PHP has the same problem when using `file_get_contents()`: https://bugs.php.net/bug.php?id=47759

In both cases, the problem is the "Chunked" transfer method. For some reason the first time GitHub uses a chunked response, the second time it is a fixed length. When we get the chunked response, we are only getting the first part of the file and not the whole thing. Ways we could fix this:

- Find a way to always get the fixed-length response from GitHub.
- Make backdrop_http_request() handle HTTP 1.1 chunked responses.
- Use a different way of downloading the file instead of backdrop_http_request().

**Comment by quicksketch** [comment]
@Gormartsen is there any way we could adapt GitHub API module to transfer the ZIP file for us? cURL can handle HTTP 1.1 chunked responses, so using it instead of `backdrop_http_request()` would solve this problem for us.

**Comment by Gormartsen** [comment]
@quicksketch Ah you got in a trouble with http 1.0 ?

I was doing patch for myself for backdrop_http_request by adding option 'protocol'.
It works perfectly when I need http1.1 but did not want to use curl.

Is this possible option?

Also it would be good update line to next release :)

**Comment by Gormartsen** [comment]
I just re read your post again. Sorry! I did not get it right. Zip file was corrupted due not properly handled chunked headers ?

**Comment by quicksketch** [comment]
Well the strange thing is GitHub isn't really following the rules. We're making the request via HTTP 1.0 (backdrop_http_request) and it is returning an HTTP 1.1 response. So we expect a non-chunked response because HTTP 1.0 doesn't support it.

But yes, the root of the problem is that we're getting a chunked response back (sometimes), and that causes the downloading of the ZIP from GitHub to fail. This is the bit that has the problem:

```
  // Copy the file down locally.
  $zip_download_result = backdrop_http_request($source_zip_url, array(
    'headers' => array(
      'Authorization' => 'token ' . $access_token,
    ),
  ));
  if ($zip_download_result->code == 200) {
    file_put_contents($directory . '/original.zip', $zip_download_result->data);
  }
```

Where `$source_zip_url` is a URL like `https://api.github.com/repos/backdrop-contrib/parsedown_filter/zipball/1.x-1.0`.

**Comment by Gormartsen** [comment]
@quicksketch pardon. I am really slow here. Just got my head in a problem.


Yes. We can add it to githubapi.module

I will work on it now.

**Comment by Gormartsen** [comment]
PS: do you need POST zip file support to?

**Comment by quicksketch** [comment]
> PS: do you need POST zip file support to?

That would be good. If we're going to be downloading the existing file with GitHub API, we should use it to upload the new file as well.

**Comment by Gormartsen** [comment]
kk. will update.

**Comment by Gormartsen** [comment]
@quicksketch 
On backdrop-ops/backdropcms.org module project is old compare to contrib version.

If I update contrib version (it handles readme via githubapi already), will you be good with updating project on backdropcms.org  ?

**Comment by quicksketch** [comment]
Yes, it would be a great time to update the module. Let's get this fixed in project module itself, make a new release, and then deploy it to BackdropCMS.org.

**Comment by Gormartsen** [comment]
kk

**Comment by Gormartsen** [comment]
@quicksketch backdrop-contrib/project#15

This is download only so far.

**Comment by Gormartsen** [comment]
@quicksketch download and upload asset finished.

But it could be buggy.

Need review and proper testing.

**Comment by quicksketch** [comment]
Awesome, thanks @Gormartsen! I won't have time to test it this week (or weekend) but in the mean time we have a temporary (serious) hack that just makes 2 requests to make sure we get the right response from GitHub. See https://github.com/backdrop-ops/backdropcms.org/commit/0dbc8fa7c0dd01212470158efba409fb9336007b.

**Comment by Gormartsen** [comment]
@quicksketch at least we have a temporary hack.

**Comment by Gormartsen** [comment]
@quicksketch issue is still active. See #1988

**Comment by klonos** [comment]
Where are we on this?

**Comment by quicksketch** [comment]
I pushed up the latest code from both GitHub API and Project module. After a few little glitches, I've confirmed that packages are now being created properly on the first time after making new releases.

I also regression tested the updating of READMEs, which initially hadn't worked quite right (they retrieved the markdown version instead of the HTML version).

To test I made new versions of both the modules that included the fixes. :)

https://github.com/backdrop-contrib/githubapi/releases/tag/1.x-1.0.4
https://github.com/backdrop-contrib/project/releases/tag/1.x-1.0.0-beta7

I also went through the last 2 months looking for any failed package builds. It looks like we only had 4 projects fail packaging in that time. Usually the packages came out okay, but a few exceptions failed. The have all now been corrected.

As noted in https://github.com/backdrop-contrib/printmpdf/issues/1, I also found an issue when packages are extremely large (that module is 45MB) that BackdropCMS.org would run out of PHP memory. I increased the capacity on the server to accommodate.

I think these problems are cleared up, please reopen if a problem related to packages crops up in the next few weeks.

**Comment by klonos** [comment]
Thanx @quicksketch 👍

**Comment by quicksketch** [comment]
We had some fallout from this change in that it broke the URLs saved in the release nodes on BackdropCMS.org. This in turn broke the Installer UI for projects that had been released since this was deployed.

The code as fixed in https://github.com/backdrop-ops/backdropcms.org/commit/36700e112307763c894064dd5152e0eb8c65d468 and then an update hook added to fix the existing broken patches at https://github.com/backdrop-ops/backdropcms.org/commit/cd610e4f8e01820d39644efed58cfe03424054f6.

The following additional packages also had incorrect links:
```
https://api.github.com/repos/backdrop-contrib/githubapi/zipball/1.x-1.0.3         
https://api.github.com/repos/backdrop-contrib/githubapi/zipball/1.x-1.0.4         
https://api.github.com/repos/backdrop-contrib/project/zipball/1.x-1.0.0-beta7     
https://api.github.com/repos/backdrop-contrib/seo_meta/zipball/1.x-1.0.3          
https://api.github.com/repos/backdrop-contrib/session_limit/zipball/1.x-1.0.0     
https://api.github.com/repos/backdrop-contrib/ejectorseat/zipball/1.x-1.0.0       
https://api.github.com/repos/backdrop-contrib/ejectorseat/zipball/1.x-1.0.1       
https://api.github.com/repos/backdrop-contrib/session_expire/zipball/1.x-1.0.0    
https://api.github.com/repos/backdrop-contrib/bot_repellent/zipball/1.x-1.0.2     
https://api.github.com/repos/backdrop-contrib/r4032login/zipball/1.x-1.0.1        
https://api.github.com/repos/backdrop-contrib/ejectorseat/zipball/1.x-1.0.2       
https://api.github.com/repos/backdrop-contrib/site_verification/zipball/1.x-1.0.1 
https://api.github.com/repos/backdrop-contrib/session_limit/zipball/1.x-1.0.1     
https://api.github.com/repos/backdrop-contrib/session_expire/zipball/1.x-1.0.1    
https://api.github.com/repos/backdrop-contrib/robotstxt/zipball/1.x-1.0.1         
https://api.github.com/repos/backdrop-contrib/smtp/zipball/1.x-1.3.1              
https://api.github.com/repos/backdrop-contrib/seo_meta/zipball/1.x-1.0.4          
https://api.github.com/repos/backdrop-contrib/easy_xmlsitemap/zipball/1.x-1.0.1   
https://api.github.com/repos/backdrop/backdrop/zipball/1.4.4                      
https://api.github.com/repos/backdrop-contrib/easy_xmlsitemap/zipball/1.x-1.0.2   
https://api.github.com/repos/backdrop-contrib/githubapi/zipball/1.x-1.0.5         
https://api.github.com/repos/backdrop-contrib/previous_login/zipball/1.x-1.0.1    
```

These have all been fixed on BackdropCMS.org, and the new updates will prevent this from happening on new releases of both modules and themes.
