### ISSUE TITLE
Need tutorial on how to convert themes to BD from D7

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#29]
Just did my first theme conversion of the Clean theme https://www.drupal.org/project/clean_theme. See it here at http://wilmurt.com/
There are a few things which need to be mentioned for persons hoping to do that as I'm sure you know. These were my personal thoughts:
- Overall it wasnt terribly difficult at all
- $block_html_id is not found but not documented as missing
- $attributes and $classes need wrapping in backdrop_attributes() and implode() respectively
- The main system menu doesnt have a `<nav>` tag
- The site name in the header somehow is wrapped in `<h1>` on the front page but `<strong>` elsewhere
- Comments on by default on basic page; it should be off I think
- Template documentation blocks need the available variables corrected. Example $picture is not available but is still documented.
- Most important, on creating a new layout, the content panel cant be found.

Clean came with a slider on the front page which is baked into the page.tpl.php. Since this template is now individual layout files, how does a them provide a slider now? Override layout templates? Provide a layout-front-page.tpl.php? This was a head-scratcher, which I still havent figured.

Finally if I wanted to list this theme on BD contrib page, whats the procedure?

I will try to put these thought into a coherent document eventually, but just wanted to record this here to highlight the issues.

**Comment by BWPanda** [comment]
I'd like to add my 2 cents regarding functionality in themes. I personally *hate* it when themes provide functionality like a slider. No offence, but themers aren't the best coders. I find implementations are often not flexible (they're made to work a certain way and that's it) and things that should be options/configurable are hard-coded.

I put my vote behind separating functionality & design. As @cellear said, themes should be interchangeable. Now that themes are no longer responsible for defining regions, there's no reason you can't easily switch themes with little-to-no changes to a site necessary.

**Comment by quicksketch** [comment]
I too like the new separation between themes and layout, and the resulting separation between themes and functionality, but it really is the case a lot of the time that the design and functionality go hand-in-hand, for example a theme intended for a brochure site is different than the theme for an e-commerce site.

I think we'll need to solve this old problem in a new way with Backdrop. Themes are likely to become "skin-only" and add-on functionality might be through new, unconventional means. One option is bundling a directory of config files to pre-configure a layout, new blocks, a slideshow, rotators, etc. With the right configuration, a theme wouldn't need additional modules for something like a rotator, since it can just convert an `<ul>` into a rotator with the right CSS/JS. Themes don't have the ability to bundle config in an automatic way currently (and I'm not sure they should), but somehow packaging config is an approach that is available to us that hadn't been an option in D7.

**Comment by danny-englander** [comment]
I'm just curious about this:

> Now that themes are no longer responsible for defining regions

So how and where do we define regions for a theme?

**Comment by BWPanda** [comment]
> So how and where do we define regions for a theme?

Through Layouts' template files. Here are the ones included in Backdrop core: https://github.com/backdrop/backdrop/tree/1.x/core/layouts

**Comment by danny-englander** [comment]
@BWPanda thanks, interesting! This seems similar to how Omega 4.x does it. I like it.

**Comment by docwilmot** [comment]
Seriously though, @quicksketch @jenlampton @cellear, we cant launch in 13 days and have talent like @danny-englander still unable to discover about basic things like defining regions. To the original point of this issue, and excuse the nagging, docs pages soon please?

**Comment by jenlampton** [comment]
@docwilmot I think we need to do two things:

1) on backdropcms.org we need to explain to people the basic building blocks of a Backdrop site:  Modules, Themes, and Layouts.  This is the *what* of backdrop. We need to clearly explain the difference between a theme and a layout, and what's responsible for what. https://backdropcms.org/layouts - was missing, and now needs some love

2) on api.backdropcms.org we need to explain the *how* for Backdrop, from the coder's perspective. For this, I've started a new book called "Developer Documentation" https://api.backdropcms.org/documentation - new, and also needs some love

As for the launch of Backdrop CMS, our priority is to get Backdrop out on Jan 15th.  After we get backdrop out, then our priority will shift back to the community tools that are needed to support it. First things first :)

**Comment by klonos** [comment]
https://backdropcms.org/layouts needs a better title IMO. How about "Build with Blocks and Layouts". I realize this puts blocks and layouts in the same documentation section, but I think they need to be explained together anyways. A more detailed "place Blocks in the regions created by Layouts" I guess.

**Comment by jenlampton** [comment]
Love it :)

**Comment by danny-englander** [comment]
I was looking at the docs and theme structure on https://api.backdropcms.org/themes and I am wondering if a theme can declare a layout? I am envisioning a layouts folder in my theme folder that then can be used in the layouts management page. I just don't want to go down a rabbit hole before I start a theme conversion.

**Comment by jenlampton** [comment]
Hi @danny-englander!  In short, no.  

The whole point of separating layouts from themes is so you can to change your theme without breaking your site.

If your site needs a special layout then you'll need to create both a layout and a theme.  The CSS for the layout will go in the layout (so that it can work with any theme) and the CSS for the theme will go in the theme (so that it can work with any layout). 

You can then change your "default" layout to use the new layout you have created, and you'll see it on every page of your site.

**Comment by danny-englander** [comment]
Hi @jenlampton, so it sounds like I can declare a layout in a custom theme? I am picturing this in my theme folder:

```
|__mytheme_two_column (folder within my theme's root)
| |____layout--mytheme-two-column.tpl.php
| |____layout.css
| |____preview.png
| |____mytheme_two_column.info
```

**Comment by BWPanda** [comment]
> The CSS for the layout will go in the layout (so that it can work with any theme) and the CSS for the theme will go in the theme (so that it can work with any layout).

Loving this new separation!

**Comment by jenlampton** [comment]
@danny-englander No.  Layouts and themes are completely separate and can not be packaged together.

Layouts are a new concept in Backdrop.  Where Drupal had modules and themes, Backdrop has modules, themes, AND layouts.  For an example of the anatomy of a layout see the core/layouts folder and the three layouts within.

All you can do to a layout in a theme is override the *.tpl.php file, or .css (just like you can with anything else).

**Comment by danny-englander** [comment]
@jenlampton - that's perfect, thank you!

**Comment by jenlampton** [comment]
Converting tutorial is located here: https://api.backdropcms.org/converting-themes Closing this issue.
