### ISSUE TITLE
BADCamp blog post collaboration

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#309]
Moving this conversation over here :) @jackaponte @thejimbirch @wesruv @mikemccaffrey @tomgrandy @quicksketch 

General points
* what is badcamp (in your words)
* why is it important / why did you go (from whoever writes the article)

Things that happened:
* Backdrop had a summit - speakers were fantastic
* Backdrop had a training class - students were enthusiastic
* Backdrop had a session - new commentary from @jackaponte improved it greatly
* Backdrop people met up for dinner - yay community <3

Please, anyone who attended BADCamp and has something for @thejimbirch to include, add a comment here :)

**Comment by wesruv** [comment]
* The 2.0 version conversation was great! We found that our development strategy is able to introduce new features without breaking API so far, so there might not be a technical reason to have a 2.0. We think we'll release a 2.0 before long because of how many awesome features we've been adding and it'd be a way to recognize that.
* Great discussion around our community culture and what that means to us, @jackaponte had a great talk explaining how our specific governance, goals, and audience is helping set us up for a great community. Plus we're clearly wonderful people.
* Thoughts around the future of how entity's view modes are laid out and improvements to the layout system. We're thinking about replacing the Manage Display tab's tabledrag interface with a layout interface that will probably very similar.
* Discussion of a custom layout builder that works through the UI, decide how many rows/columns are in a layout and how that works and save it to config for reuse.
* Discussed creating content around demo workflows and implementations for 'real world' use cases. We think example workflows and integrations with systems that our target audience is using now would help make Backdrop feel more real as a solution for them.

**Comment by wesruv** [comment]
Training day videos:
https://www.youtube.com/watch?v=kVDUsNEYM-Q
https://www.youtube.com/watch?v=E3ljH1hFgfQ

Summit Videos (quality isn't as great):
https://www.youtube.com/watch?v=6i_SCfUp_sw
https://www.youtube.com/watch?v=38tVPGVlFR0

**Comment by thejimbirch** [comment]
Presentation video:
https://www.youtube.com/watch?v=XXfe3DZZbgI

**Comment by klonos** [comment]
> Plus we're clearly wonderful people.

YEAH WE ARE!!! ❤️ 

> We're thinking about replacing the Manage Display tab's tabledrag interface with a layout interface that will probably very similar. ...a custom layout builder that works through the UI, decide how many rows/columns are in a layout and how that works and save it to config for reuse.

You guys went plotting without me? This is an amazing idea! 👍 million!!!

**Comment by Graham-72** [comment]
> Discussion of a custom layout builder that works through the UI, decide how many rows/columns are in a layout and how that works and save it to config for reuse

👍 This would be really good. For one of my sites I manually produced a custom home page layout with extra rows to produce the appearance we wanted.

**Comment by tomgrandy** [comment]
This was my first BADCamp.  Though I have been to many other DrupalCons and Camps, I had heard that BADCamp still retained the sense of community and was scaled to allow for a great deal of interaction between presenters and attendees.  To that end, BADCamp exceeded my expectations!  

The wide selection of topics to choose from, quality presenters, and the venue itself made for a very enjoyable and informative weekend.  Usually, my employer would pay for me to attend conferences like this, but this was a last-minute decision to go so it was not in the budget.  Nonetheless, I used a couple of vacation days and footed the bill because I wanted to get a feel of whether we should consider attending BADCamp instead of DrupalCon USA in the future.

As DrupalCon USA has grown, it seems to have lost its grittiness.  I remember the first few that I went to starting back in Chicago, there were a ton of people collaborating in the hallways and the spirit of community was high.  Over the years, DrupalCon USA has shifted to more like a trade show and lost some of its edge.  BADCamp brought that back to life for me.

What I liked best was the closeness you had to high-quality presenters and their willingness to engage with their audience in a fluid discussion as questions arose in the middle of presentations.  The speakers were open to shifting gears from their outline and explore ideas and go into details about specific use scenarios.

The Backdrop presentations were equally as impressive.  Though I did not get to Berkeley until late Friday night,  I did get to watch most of the Backdrop Summit and Training Class live as it was being streamed which was a big plus!  In both, the willingness of the presenters to collaborate with attendees versus merely speaking was well-received by those in attendance.  The idea-sharing for making Backdrop a better product and how to use it in its current form made for some interesting conversations.

The session on Sunday was excellent as an overview of what Backdrop can do now, the philosophy behind why it was created, and the direction it is headed in the future.  Jack's addition to how Backdrop is growing a community of users and use-case scenarios added a great deal to the presentation.  Also, the people who had questions during and after the session were greeted enthusiastically by the presenters and seemed most appreciative to have time with the creators and maintainers of Backdrop.

I look forward to coming back to Berkely or my next BADCamp and to watch Backdrop grow its community as small and midsize companies look to extend their existing knowledge of Drupal.  Many people I talked to at BADCamp mentioned that Backdrop was on their radar since D8 seems to be targeting clients with enterprise needs and budgets and leaving those small companies and non-profits to find a new CMS that they can afford to build on and maintain.  Backdrop meets that need and, to me, is the lite version of Drupal that can fill that void.

**Comment by jackaponte** [comment]
Wow--that certainly seems quite close to a blog-ready post to me! Thanks
@tomgrandy!

Still drowning in work and can't take longer to respond but feels like
folks have really covered all the bases in bullet points and other
posts--thank you so much, everyone!

**Comment by klonos** [comment]
>Wow--that certainly seems quite close to a blog-ready post to me!

👍 ...was about to say the same thing 😄

**Comment by jenlampton** [comment]
@tomgrandy  <3!!!  Please post when you are ready :)

**Comment by thejimbirch** [comment]
Yes, I agree!  You could embed the videos where you talk about them, and perhaps include a picture of Ethiopian food dinner at the end if someone took one?

Also, last paragraph, first sentence, change Berkely to Berkeley.

**Comment by tomgrandy** [comment]
Post to BackdropCMS.org?

**Comment by thejimbirch** [comment]
Yes.  I can help if needed @tomgrandy

**Comment by tomgrandy** [comment]
@thejimbirch - I do have access to post to BackdropCMS.org, but I do not see that I have permission to post to the blog.  If you don't mind, feel free to post what I wrote.  I took lots of pictures, but none of the dinner.  I think we were all too busy talking and enjoying the food!

What I see as far as Content Types are:

<img width="352" alt="screen shot 2016-11-04 at 7 34 01 pm" src="https://cloud.githubusercontent.com/assets/660545/20025677/257feafa-a2c7-11e6-9188-1ae363940faf.png">

**Comment by jenlampton** [comment]
@tomgrandy it's "Post" :)

**Comment by tomgrandy** [comment]
@jenlampton - Thanks!  Just saw that and was coming back here to delete my comment.  Are you sure you want me to post just mine or are several others posting?

**Comment by tomgrandy** [comment]
FWIW, it's up!  https://backdropcms.org/news/badcamp-experience

**Comment by jenlampton** [comment]
@tomgrandy  Having yours up is a great start! If others want to post they can, but when they have the time/energy :)

**Comment by klonos** [comment]
@tomgrandy 👍 👏 

PS: I added a few links to the things mentioned (BADCamp site, session info pages, @jackaponte's profile on b.org etc.) 😉

**Comment by serundeputy** [comment]
excellent post @tomgrandy ; thanks for your insights!

**Comment by tomgrandy** [comment]
Thanks for the additional info!  Much appreciated.

**Comment by thejimbirch** [comment]
@tomgrandy's post was delicious and amazing.  I suggest closing this issue.

**Comment by tomgrandy** [comment]
@thejimbirch - Thanks!

**Comment by klonos** [comment]
Yep, the post's been written. Thanx @tomgrandy 👍. Closing...
