### ISSUE TITLE
Updating the project node descriptions in b.org from the README.md files in GitHub.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#310]
Do project node descriptions (body field) get updated after every release created on GitHub? If yes, then how do we handle the use cases where some README.md files get updated, but the project maintainers do not necessarily create a new release (think minor typo fixes)? Having people manually also copy the changes to the project nodes in b.org is duplication of efforts.

Similarly for project node title changes. Does the node title get pulled from the .info file in GitHub? And again, does the project maintainer need to trigger the update by creating an entire release for such small things?

In general, is the update of project nodes on b.org triggered only by GitHub project releases? If so, than can we please (if possible) have it also be triggered by updates in the README.md and the .info files?

**Comment by BWPanda** [comment]
It seems that this is either already the case, or has been fixed since.

The [Pathologic module's page](https://backdropcms.org/project/pathologic) lists `1.x-1.0.4` as the latest version. On [the page](https://github.com/backdrop-contrib/pathologic/releases/tag/1.x-1.0.4) for that release in GitHub it says there has been one commit since that release was made. That commit changed some things in the README file, specifically adding the text "Backdrop's Pathologic module is based on the Drupal module's 7.x-3.x branch." and moving the License section to the bottom. Both of these changes are present on the module page on B.org.

If you can confirm that's the functionality you were wanting @klonos, you can close this issue I think.

**Comment by jenlampton** [comment]
I'm going to close this issue, @klonos please re-open if you need something more :)
