### ISSUE TITLE
Improve BackdropCMS.org navigation

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#313]
Continuing from the site redesign issue at https://github.com/backdrop-ops/backdropcms.org/issues/301#issuecomment-260980264

Proposed Menu:

---

* [x]  HOME
* [x]  ABOUT
* [x]  -- Philosophy (links to About)
* [x]  -- Leadership
* [x]  -- Release Cycle
* [x]  -- Roadmap
* [x]  -- License
* [x]  -- Contribute
* [x]  SHOWCASE
* [x]  ADD-ONS
* [x]  -- Backdrop Add-Ons (links to Add-Ons)
* [x]  -- Modules: Extend with modules
* [x]  -- Themes: Skin with themes
* [x]  -- Layouts: Build with layouts
* [x] SUPPORT
* [x] -- Backdrop Support (links to Support)
* [x]  -- Resources
* [x]  -- User Guide
* [x]  -- Developer Guide
* [x]  -- Service Providers
* [x]  -- Forum
* [x]  -- API Documentation
* [x]  NEWS
* [x]  -- Blog (Links to News)
* [x]  -- Events
* [x]  -- Mentions
* [x]  -- Weekly Meetings

---

The Backdrop nav today:

> Handbook
Modules
Themes
Layouts
User Guide
Support
News

Compare Drupal.org:
> Download & Extend
Community
Documentation
Support
Jobs
Marketplace
About

Wordpress.org:
> Showcase
Themes
Plugins
Mobile
Support
Get Involved
About
Blog
Hosting

Lets suggest major Nav links for the Backdrop main site. Post your idea of the ideal Main menu.

**Comment by docwilmot** [comment]
- Add-ons
  - Themes
  - Modules
  - Layouts
- Support
  - Documentation
  - Forum
  - Developer docs
- About
- News
- About

**Comment by klonos** [comment]
@docwilmot you have two "About" menu items. Did you mean for one of them to be "Community" perhaps? I like your proposed menus, but with a different order and some additions:

- About
  - Philosophy
  - Leadership
  - Release Cycle
  - Changelog & Roadmap
  - License
- Getting started
- Add-ons
  - Themes
  - Modules
  - Layouts
- Community
  - Get involved
- Support
  - Documentation
  - Forum
  - Developer docs
- News
  - Events

**Comment by docwilmot** [comment]
@klonos thanks, I deleted one. 

re your list, following comments (note this is just discussion):

- I'd put things in order of why I think people would come to the site, which would likely be to download stuff and get help
- It isn't common to see "About" be the first thing in a menu AFAICT. Unless its an online CV or blog or something very personal.
- Getting started would fit into "Support"
- "Community" is a nice addition.

**Comment by wesruv** [comment]
Here's what I was thinking when I was mocking stuff up:

- Handbook (Which I think I was unclear on what the intention was)
  - Getting Started
    - Installation Instructions
    - Contributing to Core (aka Core Pull Requests)
    - Developer Documentation
  - Add Ons
    - Modules
    - Themes
    - Layouts
  - Release Cycle
  - Changelog & Roadmap
  - System Requirements
  - License
- Community
  - Philosophy
  - Leadership
  - Get Involved
  - News
     - Events
- Add-ons
  - Themes
  - Modules
  - Layouts
- Support
- Download

This might not jive with the plans I think I'm hearing about moving some content to docs instead of B.org, but that's what I was thinking.

I like the word Community being up there, and I think Philosophy and Leadership fit in really well. To me Community was about the people, and how we organize our people efforts, and Handbook was more about code, tutorials, and how to's.

Was thinking Download should be in the nav because we don't know where people will hit the site from, although right now that's generally the homepage, if we play our cards right that may change. If we have more pages that apply to specific use-cases, audiences, etc, we'll be pulling more people but they won't necessarily start on our homepage.

My 2 cents

**Comment by klonos** [comment]
If we end up having the "News" item "buried" under another item instead of being top-level, here's a nice idea from the site of the very same library we use for our menus:

![smartmenus-news_badge](https://cloud.githubusercontent.com/assets/2423362/20454074/072488c6-ae8a-11e6-8efc-5843a34e57f5.png)
![smartmenus-news_badge-expanded](https://cloud.githubusercontent.com/assets/2423362/20454076/0bf16edc-ae8a-11e6-85e0-83581b754c84.png)

**Comment by tomgrandy** [comment]
@wesruv - What does the new navigation look like?  I think the above is dated since it doesn't match the mockup.

**Comment by tomgrandy** [comment]
I still think "Handbook" lacks clarity as to what the dropdown contains.  I would never go there to find out the Philosophy behind Backdrop.

To that end, a concise menu could be:

**ABOUT**
-- Philosophy
-- Community
-- Leadership
-- Release Cycle
-- Roadmap
-- License

**ADD-ONS**
-- Modules
-- Themes
-- Layouts

**SUPPORT**
-- User Guide
-- Developer Guide
-- Ways to Contribute
-- Forum
-- Resources

**NEWS**
-- Backdrop Blog
-- Weekly Meeting
-- Upcoming Events

**Comment by Dinornis** [comment]
> **ABOUT**
-- Philosophy
-- Community
-- Leadership
-- Release Cycle
-- Roadmap
-- License
**ADD-ONS**
-- Modules
-- Themes
-- Layouts
**SUPPORT**
-- User Guide
-- Developer Guide
-- Ways to Contribute
-- Forum
-- Resources
**NEWS**
-- Backdrop Blog
-- Weekly Meeting
-- Upcoming Events

+1

**Comment by tomgrandy** [comment]
@jenlampton - As point person on the menus, I think this issue is a good place to finalize since there has already been some input.  Will delve deeper, I am sure, but would like to give @wesruv a menu with links and go through the site and ensure we are not missing anything and what is there has a flow to it for the reader.  

There are a few other discussion items regarding Guidebook/Handbook at https://github.com/backdrop-ops/backdropcms.org/issues/312

**Comment by wesruv** [comment]
@tomgrandy I really like the menu structure you laid out here: https://github.com/backdrop-ops/backdropcms.org/issues/313#issuecomment-269792408

**Comment by jenlampton** [comment]
I love @tomgrandy's latest recommendation, so I have added that to the parent issue as our desired outcome. A few thoughts:

* I don't mind the about section coming first.
* we don't have a page for weekly meetings (yet?)
* the "Service providers" page was missing from your list (I added it)
* "Ways to Contribute" is sort-of the opposite of support. Leave it in About?
* I like the idea of having a community section...

**Comment by tomgrandy** [comment]
@jenlampton - How can I access the new site that @wesruv created to adjust the menus?

I could help get that knocked out today.

**Comment by jenlampton** [comment]
I don't think anyone has access to that except for Wes. We'll need to do it on the actual site once we're ready, so I don't think there's any real urgency to doing it on the dev site.

**Comment by jenlampton** [comment]
I just added the last page (https://backdropcms.org/add-ons) and our menu now matches the intended structure!!!!!  (closing issue....  finally)
