### ISSUE TITLE
Project doesn't recommend latest release as the current main release

### ISSUE THREAD

**Issue by ghost** [backdrop-ops/backdropcms.org#396]
On the project page https://backdropcms.org/project/page_theme, the project doesn't recommend the latest release as the current main release. How to fix it?

**Comment by klonos** [comment]
I think that this is either a problem with https://github.com/backdrop-contrib/project or with how that module is configured to work on b.org

So in the Project page on b.org, you have two releases listed. One is set to "recommended" while the other one "supported":

![image](https://user-images.githubusercontent.com/2423362/27152996-27762ed4-5193-11e7-838e-761eed719e41.png)

Since the Project module does not provide actual fields, I see no way to manually fix this. @quicksketch ??

**Comment by rstamm** [comment]
The project page of Colorbox offers 2 releases but there it looks fine.
https://backdropcms.org/project/colorbox

**Comment by BWPanda** [comment]
I believe this is because they are two different major releases. You just need someone to select `2` as the recommended major version on the Releases edit page:

![Screenshot 2020-05-19](https://user-images.githubusercontent.com/2385329/82302799-c1105680-99c2-11ea-993c-4c3b9f68d2d9.png)

Not sure if this should happen automatically, or just replies on manual intervention when necessary. Closing because of age and as I suspect it's the latter case.

**Comment by BWPanda** [comment]
In the meantime I've fixed that for the Page Theme module.
