### ISSUE TITLE
Survey for our newsletter subscribers

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#430]
Last week in our meeting with Facet Interactive, they recommended we send a survey to people on our newsletter, see if we could gather any useful information that could help focus our efforts where it's needed most. 

# 5 Questions we have for our followers 

1) What is your relationship with Content Management Systems? 

* back-end CMS developer
* front-end CMS developer
* I own or manage a website that uses a CMS
* I'm thinking about adopting a CMS

2) Which CMSs have you used in the past?
* Drupal
* WordPress
* Other [write in]

3) What languages do you speak?

* English
* Other (please specify)

4) How recently have you tried Backdrop CMS?

* I'm playing with it right now!
* In the past 6 moths 
* in the past year
* I haven't tried it yet.

5) When are you planning on launching a Backdrop site?

* I already have!
* I'm working on one right now
* in the next 6 moths 
* in the next year
* no plans yet

6) If you have a site you are thinking about moving to Backdrop, are any of the following preventing you from doing so right away?

* I want to see more sites running on Backdrop
* I want to see more big brands adopting Backdrop
* I want to see more people I know and trust adopting Backdrop
* I want to hear more success stories about people who have already adopted Backdrop
* I'm still not sure of the differences between Drupal & Backdrop
* I'm waiting for more modules themes & layouts to become available.
* I'm waiting for the right project to come along
* Other [ write in field ]

Anything else?

**Comment by olafgrabienski** [comment]
> 4. If you have a site you are thinking about moving to Backdrop, what’s stopping you?

The question sounds a bit negative in my opinion, assuming that something is stopping the move to Backdrop in any case. Maybe we should ask that before, something like this (could need better English):

*If you have a site you are thinking about moving to Backdrop, is there something stopping you? If yes, what are the reasons?*

**Comment by jenlampton** [comment]
Excellent suggestion. What about this: `If you have a site you are thinking about moving to Backdrop, are any of the following preventing you from doing so right away?`

I think without the word "stopping" it also sounds a little less negative.

**Comment by olafgrabienski** [comment]
Yes, I guess that's better.

Btw, I also wanted to suggest a "Other" option for this question. Don't know if the new sentence would still be convenient then.

**Comment by alexfinnarn** [comment]
I like the current questions and would like to know one or two more opinions from users/potential users. 

If you've already heard of Backdrop...
5. What would you say its mission statement is?
6. What weaknesses do you think the project has currently?
7. What strengths do you think the project has currently?

I'm writing a blog post I will put on my personal site about reactions I've gotten to those questions, and I'm surprised when I get contradictory answers sometimes. "They just don't want to change (vs. Drupal 8 code)." vs. "They've changed too much to migrate D7 code." as an example. 

I forgot to ask the questions above before starting conversations with people so I'd like to know what people think. 

It might be useful to make the strength/weaknesses multiple choice instead of free response since people might feel uncomfortable listing bad things...but maybe not...depends on the person. Probably more useful feedback as a free response, but I would like to see what people in the core and contrib groups responses would be or what people have told them. 

Also under #3 "in the next 6 moths" makes me think I have to kill moths to launch a Backdrop site, lol. 

Some potential other questions...

- What is your number one killer feature a CMS should have?
- What CMSs have you used in the past?
- Do you go to any tech-related meetup groups? Some way of knowing where people talk in general about CMS stuff...can lead to tele-presentations in their local user groups. 
- Some fun question about dragons at the end...I love whimsy, and I think dragons are safe whimsy with little to no triggers/triggering. 
- Links at the end to the forum/Gitter/weekly meetings or other follow-ups. 

> Btw, I also wanted to suggest a "Other" option for this question.

I think adding "Other" free-form text field for a lot of questions might be useful. By gauging the estimated number of responses, then you could think of how tedious going through and coding those free-form responses would be. 

Finally, and probably not in time/too much work for the survey, have you ever thought of integrating some sort of official Backdrop update notices into the notifications? Checks are done for new  Then on any site running Backdrop, you could advertise the survey and future beta testing/feedback messaging. 

I'm wasn't subscribed to the newsletter until now, but adding feedback into core would provide an additional way of getting more eyeballs and responses.

**Comment by Graham-72** [comment]
Do we not want responses from people who have already launched Backdrop sites? I am thinking of another possible option at question 3.

Maybe 'launched' is too limiting. Perhaps we could get useful information from those who have implemented a test site or seriously evaluated Backdrop in some way.

**Comment by jenlampton** [comment]
Thanks all for your help drafting he survey, we've gotten some excellent responses already :) Closing this issue!
