### ISSUE TITLE
Permission to be able to close issues in contrib?

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#44]
In d.o, one could close an issue even if they were not the owner/original author. How are we to handle this in contrib over at github? Asking because I wanted to close https://github.com/backdrop-contrib/pathauto/issues/1 as a dupe but couldn't.

**Comment by quicksketch** [comment]
Hi @klonos! You're right, permissions are very weak over here at Github, that's why we have the separate (empty) repository "backdrop-issues" to which everyone is given commit access. That allows everyone to tag, close, and edit issues together.

The Backdrop contrib repository is set up somewhat similar, all contrib authors who can commit to one project can commit all projects. We're including the list of maintainers in the README.md files as a social policy that you shouldn't commit to project for which you're not listed as a maintainer without requesting permission first. Technically, all authors can commit to all projects. While that is discouraged, it also comes with the up-side that contrib authors can also collaborate to help organize and manage issues. But unfortunately, you'd need to be in the contrib authors group first before you have that permission. :frown:

I haven't figured out a way to deal with a situation you've just described: a community member who could help organize issues but is not (yet) a contrib author.

In the mean time, there are two options: ask someone else to close the issue, or undertake a small port or module and apply to the group as others have done.

I know this is quite inconvenient. You shouldn't have to port a module in order to close an issue. Github is just requiring us to get clever with our processes. I'm definitely open to ideas.

**Comment by klonos** [comment]
> I'm definitely open to ideas.

How about allowing people that are long-time d.org users proven to help with issue triaging but not coders (hint: talking about me) be part of the https://github.com/backdrop-ops organization (that includes contrib)? Huh?

**Comment by docwilmot** [comment]
> How about allowing people that are long-time d.org users proven to help with issue triaging but not coders (hint: talking about myself) be part of the https://github.com/backdrop-ops organization

I'd second that. I'd prefer to have @quicksketch building a better Backdrop and have a @klonos haunting the queues. Better distribution of resources.

**Comment by quicksketch** [comment]
> be part of the https://github.com/backdrop-ops organization (that includes contrib)? That should give enough permissions. Huh?

Unfortunately the `backdrop-ops` group doesn't grant access to the `backdrop-contrib` group. There is a repository called `contrib` inside of `backdrop-ops`, but that's just for the application process. On Github, there's literally no way to let people tag or organize issues in any repository to which they don't have commit access. The limitation is pretty annoying for those used to drupal.org's granular system.

But, totally agreed, we need more distribution of responsibility, at a lot of levels actually. I'll chat with @jenlampton on options.

**Comment by klonos** [comment]
Thanx for taking the time to explain Nate. Patiently waiting for the outcome of the talk with Jen. Perhaps this is an issue for the weekly agenda?

**Comment by jenlampton** [comment]
Good idea @klonos. We do need to solve this problem. Here's what we've come up with so far:

1) Add stipulations around how a non-coder gets commit access to the contrib group. @quicksketch proposed that the applicant needs to get one recommendation from another person who already has commit access to the contrib group.

2) Applicant needs to agree to the same contributed project author agreement as coders.

3) Applicant needs to additionally promise that should they ever want to author some code posted in the Backdrop contrib group, they will also undergo the code-review process at that time.

**Comment by klonos** [comment]
> ...the applicant needs to get one recommendation from another person who already has commit access to the contrib group.

Anybody willing to recommend me? :)

**Comment by klonos** [comment]
> 2) Applicant needs to agree to the same contributed project author agreement as coders.

How/where do I do that?

> 3) Applicant needs to additionally promise that should they ever want to author new code in the Backdrop contrib group, they will also undergo the same code spot-check process a new contributor needs to undergo at the time they add the code.

Cross my heart!

**Comment by jenlampton** [comment]
@klonos can you please open an issue over at https://github.com/backdrop-ops/contrib/issues/new requesting access to the contrib repo for the purposes for maintaining isses? I'd be happy to recommend you, and in that queue @quicksketch will ask you to agree to the agreement :)

**Comment by klonos** [comment]
Already did (see the linked issue a couple of comments up?). Here it is: https://github.com/backdrop-ops/contrib/issues/45

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop-ops/contrib/issues/45.

**Comment by klonos** [comment]
Yep, thanx once again.
