### ISSUE TITLE
Facebook JS Error: Sending non-standard event 'ViewCategory' instead of preferred 'trackCustom'

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#458]
https://backdropcms.org/modules

<img width="1463" alt="screen shot 2018-07-10 at 2 08 09 am" src="https://user-images.githubusercontent.com/2423362/42462607-1aad2112-83e7-11e8-8aee-0280878d3269.png">

**Comment by jenlampton** [comment]
We aren't doing anything with facebook marketing on the backdrop site. Could this be caused by a browser extension you are using? Does it happen on all your browsers, or just this one?

Can you also please add steps to reproduce? Is this after running a search or when first visiting the page? Is your cursor in the field? I can't reproduce on any of my browsers.

**Comment by klonos** [comment]
This was something sillier than expected: an autocomplete entry 😛 ...sorry for the false alarm.
