### ISSUE TITLE
Upgrade b.org to the latest version.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#463]
We are currently on ~1.9.6~ 1.9.5. We should not be lagging too much behind the current version, then we risk bigger changes and greater possibility for breakages.

Besides the actual task of upgrading the site, can we also set another task/policy to make best effort (as time/resources allow) to be upgrading to the latest prior minor release once the next is released? In other words, lets update to latest 1.10.x after 1.11.0 is released.

I think that setting up an automated service or a manual task for visual regression and broken links testing would help towards that goal. Are there any 3rd party services that offer that for free to open source projects?

**Comment by alexfinnarn** [comment]
> I think that setting up an automated service or a manual task for visual regression and...

I tried to sign up for an open source account with Applitools, https://applitools.com/pricing, but they've only sent me marketing emails. Worth a shot though. 

On this note, I will link to https://github.com/backdrop-contrib/xmlsitemap/issues/17 where I wanted to add a test runner template for using Travis CI in contrib modules. A lot of them have SimpleTests in the modules and I think Behat tests are easy to write if all you have to do is create the ".feature" files. 

I made some scripts that would help to make such a template, but how does that fit into the 3rd party services used in core vs. contrib? On d.o. I think the same test runner was used for both core and contrib, but for Backdrop I can only see tests running on the core project.

For instance, individual users can apply for an Open Sauce account to host a Selenium Server, but it would be nice to have a Bacldrop contrib account that could be placed on contrib projects...Open Sauce is just an example, but it does have usage limitations like most 3rd party services with open source pricing would have.

With the way the contrib repo is setup, a "testing czar" could monitor the test runner across the projects, but I think it would have to be done manually per GitHub repo rather than just uploding the code like si done on d.o.


...a good ramble there, but you could try Applitools out to see how getting an open source account goes. I will add anything I come up with to the XML Sitemap repo and then propose some templates be added to the porting a module process if my plans succeed.

**Comment by quicksketch** [comment]
Note as of lately we've been up-to-date fairly frequently, mostly because recent updates included security fixes. BackdropCMS.org is currently running the latest: 1.12.3.

**Comment by jenlampton** [comment]
closing this ticket.
