### ISSUE TITLE
sanitize.backdropcms.org: Add sanitized DBs for localization & api & forum sites

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/backdropcms.org#470]
@larsdesigns can you set up cron jobs to run https://github.com/serundeputy/sql-dump-sanitize for:

* https://github.com/backdrop-ops/localization
* https://github.com/backdrop-ops/api.backdropcms.org
* https://github.com/backdrop-ops/forum.backdropcms.org

So we can leverage more developers to help with issue queues.

thanks!

----

Alternatively if someone wants to give me access to the server(s) I can help with these tasks and deploys to b.org, localize, and forum (I understand if it is too many cooks in the kitchen).

**Comment by larsdesigns** [comment]
Okay, I am happy to help. I should have time tonight.

**Comment by olafgrabienski** [comment]
Are the cron jobs already set up? I'm asking because I'm planning to work on the localization server again.

**Comment by larsdesigns** [comment]
Not for these sites. I will try and get some time in tomorrow evening.

**Comment by jenlampton** [comment]
Hi @larsdesigns we're having requests for sanitized DBs for these other sites again. Can we get this ticket back on your radar? I'm going to make a few manual backups and put them in the sanitize location so people can start working, but it would be good to get the daily backups running.

**Comment by stpaultim** [comment]
Just for the record, in Gitter yesterday/today:

@larsdesigns asked:
> @serundeputy Just wanted to see what I can do to move this along: backdrop-ops/backdropcms.org#470

My reply:

> @larsdesigns - My understanding is that @serundeputy has written this script to generate some sanitized databases. He is looking for a cron job (daily or weekly - I am not sure about this) to run the script and create fresh copies of the database for people to use.
> I’m assuming that you would need to set up the cron job and possibly create an accessible place for contributors to acccess the dumps. I think I was the one that triggered @jenlampton to create the last batch.
> I don’t know if this is helpful or just restating things you already understand.
> We’re just looking for a way that folks like me can spin up a local version of the forum to write PRs with a relatively recent version of DB.

@serundeputy added:

> yes; @stpaultim has it right set up additional cron jobs to run the backups and sanitized backups of b.org, api.b.org, and form.b.org. Put them in the directory that serves sanatize.b.org so developers can grab them and help us work on those sites

**Comment by larsdesigns** [comment]
1. Completed the cron jobs by creating a job within the crontab for each site user account within the host.
1. Updated the index page to loop through multiple site file archives and database dumps. 
1. Added the database name to the files archives file name so we know of which site it belongs. 
1. Created the sanitize linux user account and moved the sanitize.backdropcms.org code to it so that it is consistent with the other sites. Used symlinks  to the access the database dumps and files directory archives. 
1. Created instances of the sanitize script in each user account to correspond with the site.
1. Unfortunately, the sanitize script does not run on the localize.backdropcms.org site because it seems to be Drupal site and not a backdropcms.org site.

1. Created a pull request for @serundeputy to merge in my changes as found in my fork: https://github.com/serundeputy/sql-dump-sanitize/pull/9. 
1. Updated the database user privileges so that they can create and drop temporary databases for each site.
1. Updated the database dump in the script so that creates its own unique temporary database table. Introduced a constant that is define in the config.ini file to handle the temporary and unique database name. 

The end result is that there are downloads available for sanitized database dumps and file directory archives for api.backdropcms.org, backdropcms.org, and forum.backdropcms.org.

The files should update every hour. I will check back to make sure all the cron jobs are running. 

@serundeputy 

### To Do: 

1. Send linux user credentials for the new sanitize user account to @jenlampton and @quicksketch. Also add their ssh keys to the account. 
1. Monitor the cron jobs using Nagios.

**Comment by larsdesigns** [comment]
Looks like the API cron jobs are running every hour.

```
-rw-r--r-- 1 api api 14797596 Oct 15 12:06 api_backdrop-October-15-2019-70633-sanatized.sql.gz
-rw-r--r-- 1 api api 14797534 Oct 15 13:06 api_backdrop-October-15-2019-80634-sanatized.sql.gz
-rw-r--r-- 1 api api 14797424 Oct 15 14:06 api_backdrop-October-15-2019-90634-sanatized.sql.gz
```

```
-rw-r--r-- 1 api api 1061497 Oct 15 12:45 api_backdrop-files-October-15-2019-74500.tar.gz
-rw-r--r-- 1 api api 1061497 Oct 15 13:06 api_backdrop-files-October-15-2019-80601.tar.gz
-rw-r--r-- 1 api api 1061497 Oct 15 14:06 api_backdrop-files-October-15-2019-90601.tar.gz
```

**Comment by larsdesigns** [comment]
Added ssh keys to auhtorized_keys for @jenlampton and @quicksketch.

**Comment by larsdesigns** [comment]
I double checked and the cron jobs are running every hour for backdropcms.org, api.backdropcms.org, and forum.backdropcms.org.

**Comment by serundeputy** [comment]
we have the backups running or b.org, API, and Forum.
closing ... re-open if necessary.
