### ISSUE TITLE
number of commits/comments on home page

### ISSUE THREAD

**Issue by charlie-jones** [backdrop-ops/backdropcms.org#530]

**Comment by charlie-jones** [comment]
Should be 22,571 commits instead of 3,984, comments should _not_ be 22,455 (because that is number of commits)

**Comment by serundeputy** [comment]
Hello @charlie-jones !

thanks for filing this issue!

As you know Backdrop is a fork of Drupal.  So, we decided to calculate the number of commits to Backdrop as commits after the fork `Get the number of commits to Backdrop since 1 September 2013` ...  https://github.com/backdrop-ops/backdropcms.org/blob/master/www/modules/custom/borg_project_metrics/borg_project_metrics.module#L130

**Comment by charlie-jones** [comment]
Hi @serundeputy,

Thank you for the reply! Yes, that would make sense. Just thought it is funny how the # of commits is soooo similar to the comments on website. I think what you said is right though 👍
