### ISSUE TITLE
Allow installing contrib via project installer in tugboat demos

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/backdropcms.org#556]
Currently the installs fail with a permissions issue. It would be great to allow people to see how easy it is to extend Backdrop through the Project Installer and test out some contrib modules at the same time.

**Comment by BWPanda** [comment]
Here's a PR that fixes this: https://github.com/backdrop-ops/backdrop-tugboat/pull/6

The issue was simply that it was changing the owner of `DOCROOT` (which is a [symlink](https://github.com/backdrop-ops/backdrop-tugboat/blob/master/.tugboat/config.yml#L40) to `TUGBOAT_ROOT`), not `TUGBOAT_ROOT` itself.

**Comment by quicksketch** [comment]
Nice! Well the current `chown` doesn't seem to do anything (effectively). Let's try it out!

**Comment by quicksketch** [comment]
It works!

![image](https://user-images.githubusercontent.com/100206/74986646-6ee18880-5407-11ea-8d64-3e09a41b7b3d.png)

Nice one @BWPanda!

**Comment by stpaultim** [comment]
I just tested this and it worked great. It's crazy cool to be able to do this!!!! 

Thanks.
