### ISSUE TITLE
Improve blog post for version 1.14

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#578]
@herbdool asked

> @stpaultim Is it too late to ask for an elaboration of this? "This is a great improvement that allows fieldable files to be uploaded directly. "

Opening this issue for feedback or ideas on how to improve the [blog post](https://backdropcms.org/news/backdrop-cms-114-released). In particular, I'd be open to ideas on how to elaborate on either "Core fieldable file entity bundles” or “Trusted Host Patterns.”

I probably copied that line from elsewhere, so I'd love ideas on how to make it better. 

(This issue can be closed if inactive for 2-3 weeks - it's a very short term issue).

**Comment by BWPanda** [comment]
Suggestions...

Under "Default editor role for every new site", change:
> If you are upgrading an existing site you will not get this role as it is part of the standard install profile.

to

> Existing sites won't have the new role by default, but it can be added manually at `/admin/config/people/roles`

(or something; I just don't like the "you will not get this role" wording, and some people might not know what the standard install profile is/means).

Under "New welcome block on the site dashboard", change:
> We've added a new welcome block to the dashboard (the dashboard module was introduced in Backdrop CMS version 1.13 and you may still need to enable it on existing sites).

to

> A dashboard was introduced in Backdrop CMS version 1.13. Existing sites need to enable the Dashboard module to use it. In this release we added a new welcome block to the dashboard.

Remove the "To see all the other improvements packaged in the 1.14.0 release, take a look at the release notes!" line (since no other improvements are mentioned in the release notes), or consider linking instead to the [1.13.4](https://github.com/backdrop/backdrop/releases/tag/1.13.4) release which was released simultaneously and has all the extra bug fixes, etc.

**Comment by stpaultim** [comment]
Thanks for these suggestions. I could still use some help with "Core fieldable file entity bundles” or “Trusted Host Patterns.”

**Comment by stpaultim** [comment]
Going to close this, since it's been a month.
