### ISSUE TITLE
Ship Backdrop with a 'Blog' profile

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#58]
I have no solid evidence but considering the huge market share difference between Backdrop and Wordpress, I'm guessing a whole bunch of people either want Blog software, or have come to associate 'CMS' and 'Blog software' as similar things. Being able to demonstrate right at install that you can build a great push-button blog with Backdrop should be a huge plus.

Related is https://github.com/backdrop-ops/backdropcms.org/issues/56#issuecomment-93853228, https://github.com/backdrop/backdrop-issues/issues/870 and https://github.com/backdrop/backdrop-issues/issues/99 which all have to do with more nimble packaging of features (distributions, project packages etc.). We **could** then also ship naked Backdrop with a home page that then says 'OK now what do you want from your site' and allows that to be automatically built from some sort of packaging arrangement. But I'd still say a Big Ole Install a Blog Button would be my preference.

**Comment by quicksketch** [comment]
I think I'd like to define what makes a "blog" profile and evaluate the individual pieces as just being in the default profile. The default installation profile already is a blog in most senses. What parts are missing that you would expect from a blog, and would any of those be inappropriate for the default profile?

**Comment by docwilmot** [comment]
See the typical instructions [for starting a blog](https://www.siteground.com/tutorials/blog/drupal.htm) [with Drupal](http://www.commercialprogression.com/post/how-create-blog-drupal). Several steps, several modules to tweak. 

I mean create a profile 
- that produces all of those steps, and includes all of the essential modules and blocks preconfigured
- A Blog content type
- and says "Blog" everywhere to make it obvious (pathauto configured, a "My Blog articles" block, etc).

It would be even better if like Pantheon, a user could select from a bunch of approved profiles in the installer...

**Comment by quicksketch** [comment]
I think we could meet the need of creating a "blog" content type by simply renaming "Article" to "Post" in the default profile, as suggested in https://github.com/backdrop/backdrop-issues/issues/742. The only thing remaining from the first tutorial would be creating a block of recent posts (easy enough). The second tutorial is equally simple only it describes making a blog section instead of using the homepage as the blog. That sounds like one possible option as well (bundle a default front page layout instead of using the blog as the homepage).

There just don't seem to be enough steps to warrant a different profile. I think the out-of-box experience *should be a blog*, because almost all sites have one anyway.

**Comment by quicksketch** [comment]
Oh, this should probably be in the backdrop issues queue, not backdropcms.org?

**Comment by docwilmot** [comment]
> Oh, this should probably be in the backdrop issues queue, not backdropcms.org?

True that.
