### ISSUE TITLE
Discussion: Alternatives to Gitter

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#587]
I am opening this issue, because the discussion of moving off of Gitter keeps coming up from time to time and we don't currently have a good issue to capture the thoughts and history of this discussion. 

A number of users have complained about the user experience with Gitter, especially when things get busy. We only have a single Gitter channel and it can get hectic there on occasion. Some chat tools offer threading options or multi-channel options that we just don't seem to have in Gitter. 

@jenlampton - has expressed reservations about moving to anything other than Slack. My understanding is that her concerns are mostly about using a tool that people are comfortable with and not loosing people during any kind of move. 

@herbdool has done some research on open source alternatives. Some of us tested [Zulip](https://zulipchat.com) as an open source alternative with a free hosted option for open source communities. 

Related discussions:
[#1426](https://github.com/backdrop/backdrop-issues/issues/1426) - Live chat options: Gitter / Slack / MatterMost / HipChat / Ryver

https://github.com/backdrop-ops/backdropcms.org/issues/18 - Discussion: Where should we start a discussion forum?
https://github.com/backdrop-ops/backdropcms.org/issues/510 - [ONGOING] Keep dragonbot (hubot) up to date

**Comment by laryn** [comment]
I think Zulip checks a lot of boxes, perhaps even the weekly meeting videos (with integrated Jitsi Meet, or optionally Zoom integration), data import from Gitter, etc.

**Comment by BWPanda** [comment]
I agree. From what I've seen/read Zulip seems like a very appropriate candidate. Does it have any cons that we know of?

**Comment by jackaponte** [comment]
I've never used or seen Zulip; it sounds like it's likely a good fit, but I _have_ heard a few folks complain about the "email threading model" they use, saying it's difficult to navigate.

I'll also note that I greatly enjoy Mattermost (i.e. open source Slack) for both CiviCRM project chat and Palante internal chat. It can be self-hosted (both of those MM instances are), but they've also got a greatly discounted nonprofit version for which we might qualify: https://mattermost.com/nonprofit/

**Comment by klonos** [comment]
My only (personal) objection with MatterMost is that it does not seem to be supported by https://getstation.com (not currently at least - not sure if planned to be in the future).

Does it support threaded discussions @jackaponte? The problem we are trying to solve here is that it seems that the community seems to be growing, and keeping all discussion in a single thread has started becoming a pain.

**Comment by klonos** [comment]
...has https://rocket.chat been considered?

> **Discussions**
> Are basically new sub channels that inherit permission from the parent channel and have its creation announced on the parent channel.
> 
> **Threads**
> Will exist on the same channel. They will replace/enhance the reply action we have now, but add the parent message property to the messages, so they can be displayed on the sidebar.
> 
> Both these features will be toggleable. e.g. turn on only threads but not discussions.

**Comment by herbdool** [comment]
Here are some of the ones to compare:

* Zulip
* Mattermost
* Rocket.chat
* Riot.im (https://about.riot.im)

We will to compare them based on needs and wants. They need GitHub login, nonprofit deal, a bot?... It's not clear if it needs to be a cloud version or if someone is willing to self-host. If the latter is an option then it helps expand choice.

I liked a lot of things about Zulip when I tested it, including the threading like emails. Plus the nonprofit access to their cloud version helps and they have integration with GitHub for logging in. 

Wants: chatbot, threading, mobile apps.

I'm still going to put this in a spreadsheet to help decide.

**Comment by herbdool** [comment]
This page makes me like Zulip even more https://zulipchat.com/for/open-source/

**Comment by jackaponte** [comment]
To be clear, I defer to folks who are on the Backdrop Gitter way more than I am, as well as anyone who would be maintaining either the cloud version or the self-hosted installation. 

If most folks who use Backdrop Gitter frequently want to go with Zulip, sounds good to me! I'm not all too attached to Mattermost, just do know and like it well as an open source Slack clone.

The rest of this isn't an argument for Mattermost but rather info responding to @klonos' questions and for Herb's spreadsheet, in case it's useful.

> Does it support threaded discussions @jackaponte? The problem we are trying to solve here is that it seems that the community seems to be growing, and keeping all discussion in a single thread has started becoming a pain.

Mattermost supports both multiple channels and threaded conversations within those channels; the threaded conversation functionality sounds similar to what you describe [above](https://github.com/backdrop-ops/backdropcms.org/issues/587#issuecomment-542444706) for Rocket.chat. It also has mobile apps and a chatbot (at least in our self-hosted version but I think it came with it out of the box and can be extended in ways I'm not familiar with.

**Comment by stpaultim** [comment]
We could also make use of more Gitter channels. Right now, we try to keep almost all of the conversations in one channel/room. Adding/using more channels might be helpful. 

I understand that this not an ideal solution, but it would give us a little more room to grow without the overhead of setting up an entirely new system and reduce the risk of loosing people along the way. I know that one of the concerns about moving is that we'll loose a lot of people who have created accounts in the past, but are inactive right now.

**Comment by BWPanda** [comment]
The problem I see with multiple Gitter channels is discoverability. Threads you can see in the sidebar whether you're a part of them or not (from what I understand), whereas you have to join a channel for it to show up I believe.

As for inactive members, I don't see them being able to catch up on one long discussion, so maybe threaded discussions would help them too...

**Comment by olafgrabienski** [comment]
For people who want to try Rocket.Chat, there is also https://drupalchat.me.

> This project is community driven and aims to replace the proprietary solution Slack for various reasons.

See https://www.drupal.org/drupalchat for more information.

**Comment by olafgrabienski** [comment]
> ...has https://rocket.chat been considered?

>> Discussions ...
>>Threads ...
>> Both these features will be toggleable. e.g. turn on only threads but not discussions.

I've had a quick look at drupalchat.me. Discussions don't look helpful at all, Threads could work but they're not very visible.

**Comment by herbdool** [comment]
I've got a simple spreadsheet https://ethercalc.org/jthflo2ls7vz comparing the open source chats I could find. I haven't tried them all; only Mattermost and Zulip. I'm partial to Zulip mostly because it checks all the key boxes (github integration) plus it makes it super easy to discover threads.

I'm guessing that we'd probably prefer the cloud version of whatever we choose to lessen the workload.

All I know is that I'm done with Gitter. The app is terrible.

**Comment by klonos** [comment]
> This page makes me like Zulip even more zulipchat.com/for/open-source

Indeed! 👍

**Comment by jackaponte** [comment]
> This page makes me like Zulip even more https://zulipchat.com/for/open-source/

That page makes many great points that seem quite relevant to the Backdrop community; thanks for sharing that page, @herbdool and @laryn!

Agreeing with others, looking at that spreadsheet, Zulip seems like the best fit, especially since I didn't realize the Mattermost nonprofit deal is self-hosted only.

**Comment by herbdool** [comment]
It seems that threaded conversations are in beta for Gitter. I've enabled the beta feature and testing them out a bit. It seems similar to other implementations of threading, yet I'm not that impressed with the ability for this type of threads to be useful for a distributed group across time zones. It's hard to discover threads - they aren't labelled in any way; we can't get a list of them in a sidebar or something. Someone would need to still scroll through the entire conversation to see if there's anything relevant.

**Comment by BWPanda** [comment]
Can someone with access to the appropriate repo/email address setup a Zulip chatroom for us to try? Seems appropriate timing since Gitter's still/again down...

**Comment by laryn** [comment]
I'm interested in testing out Zulip if we get a chatroom set up.

**Comment by jenlampton** [comment]
What do we need to get this started?

**Comment by BWPanda** [comment]
Do we want to import our Gitter chat? https://zulipchat.com/help/import-from-gitter

Either way, looks like we need someone with access to Backdrop's email/repo to set it up: https://zulipchat.com/new/

**Comment by BWPanda** [comment]
At the same time, email sales@zulipchat.com about getting the Standard account for free as a non-profit: https://zulipchat.com/plans/ (see FAQs at bottom).

**Comment by jenlampton** [comment]
Does this work for you? https://backdrop.zulipchat.com/#narrow/is/private

**Comment by BWPanda** [comment]
@jenlampton "You need an invitation to join this organisation."

**Comment by herbdool** [comment]
I get that message too. The initial part of signing up with my Github account works tho.

**Comment by stpaultim** [comment]
Same for me.

**Comment by jenlampton** [comment]
I don't see any way to make this public. I'm going to add the un/pw to the Backdrop 1Password so others can log in and give this a try.

**Comment by herbdool** [comment]
I could take a look but I don't have access to the 1Password.

**Comment by jenlampton** [comment]
@herbdool I'm going to send an invite to your .name email address. If that's not the one you want please send a different one to info@backdropcms.org :)

**Comment by stpaultim** [comment]
Anyone should be able to join now without permission.

**Comment by larsdesigns** [comment]
I am leaning towards rocket.chat on-prem implementation. It is something that we can host on our existing server using the Debian package, have access to all of the features, and avoid hosting vendor lock-in. 

We would also have full admin control and access to develop for it should we want to integrate with something. 

The apps seem to have the same features as the other SASS solutions mentioned above. It looks like IRC clients can connect to it also should anyone crave a vintage experience. 

The cost is that it is another system to maintain. But it seems to update well using aptitude.

**Comment by larsdesigns** [comment]
Perhaps getting it up and running as their free vendor hosted community tier to gather feedback would be good for evaluation. As what is going on with Zulip right now.

**Comment by olafgrabienski** [comment]
@larsdesigns re Rocket Chat: What do you think of threaded discussions / topics? AFAIK, Zulip is the only tool so far where individual topics are easy to follow even after days. It's kind of a killer feature. I don't know Rocket Chat very well but on Rocket Chat for Drupal (drupalchat.me), how threads are implemented, they didn't look very helpful, i.e. no big difference to Gitter, Mattermost and so on.

**Comment by BWPanda** [comment]
Also, on https://rocket.chat/pricing#self it says 'Push Notifications = 1000 monthly' for the free community edition. What does that mean? Is a push notification a notification I get on desktop or mobile when there's a new message? If so, is 1000/month for each user, or for everyone?

**Comment by larsdesigns** [comment]
@olafgrabienski, It looks like the threads feature is well thought out. However, I have not found it exceptionally helpful except to find replies quickly. Because of my years on IRC, my mind is not really conditioned to think about chat threads. However, it looks like a helpful feature to have.

I especially like the layout and style options for the mac app and the memory usage is much much lower than Slack for example. The web interface seems acceptable also. It is very much like Slack like but the differences seem to be improvements. 

I am not sure about the push notifications. The way it is presented in the pricing it seems to be an account limit but it is not clear to me either. I will reach out to them and get a solid answer. 

However, I have heard through the grapevine that they sometimes provide pro or enterprise level plans to Open Source communities for free. This is something we can investigate if the software is found to be acceptable or great for the community. 

If we host the on-prem server ourselves, the limits would be defined by our hosting resources. Push notification would  be limited  by bandwidth usage I suppose. Linode provided bandwidth would seem to be more than adequate. Perhaps this is something the community can grow into and starting with Rocket.Chat hosting would be fine for a while. 

I am thinking that the push notifications are only for the mobile apps because of the way the mobile operating systems handle memory it relies on push notifications. It seems to me that when the desktop Rocket App is open, it is polling for notifications like like other messaging apps. 

As a side note, I am just exploring this as an option and I am not yet making any recommendations. It caught my attention because we can potentially host it on our own which is unique and the software is Open Source. It kind of has that IRC-community-OSS feel about it which is attractive to me. This is all personal preferences though. 

I will evaluate the IOS mobile app and post my thoughts about it.

**Comment by BWPanda** [comment]
While I'm generally in favour of OOS for privacy and owning-your-own-data reasons, the maintenance concerns me. As we've heard in recent discussions/meetings, getting the volunteer community to work on things can be difficult (lots of open bugs, half-finished PRs, etc.). So adding more work to the mix (especially server admin-based work) sounds like it'll take even more efforts away from maintaining and enhancing our code (i.e. Backdrop, our websites, etc.).

I'm not so concerned with another company handling our chat data. I mean, GitHub handles all our code, issues, PRs, etc. anyway...

**Comment by herbdool** [comment]
When I researched the different options (see https://ethercalc.org/jthflo2ls7vz) I noted that Rocket.chat didn't meet a couple of the criteria, namely login via github, free for non-profits (seems like we'd still need to pay). I also don't think self-hosting is realistic for this small community at this point so I think that's out.

But we've been testing out https://backdrop.zulipchat.com/ for a couple weeks now and it seems to meet all our needs. I can't think of anything that other chat programs offer that Zulip doesn't provide.

**Comment by larsdesigns** [comment]
These are all good points to consider.

**Comment by herbdool** [comment]
@stpaultim has there been any discussion in the weekly meeting on how to proceed on this? Should we continue testing Zulip for awhile? How long before it comes to a decision?

**Comment by BWPanda** [comment]
There was mention of it a week or so back. Nothing much said other than an acknowledgement of this issue. One suggestion was for people to 'vote with their feet' to get an idea of if Zulip is what people want, but my problem with that is that most people (myself included) still post to Gitter since that's where most people look and are active. Other suggestion was a PMC vote, which I agree is the way forward, though @jenlampton and @quicksketch both admitted they haven't really tried Zulip...

**Comment by jenlampton** [comment]
I have opened a PMC issue, and stated `I'd like to ask that everyone here try Zulip for a while so that we'll be able to make an informed decision.` We usually leave PMC issues like this open for 2 weeks (for discussion) before a vote.

**Comment by jenlampton** [comment]
I tried Zulip again and still wasn't able to sign in with my GitHub account. The interface does suggest that it is possible, but I still end up getting redirected to a registration screen every time. :( I'll try again later, but suspect this may be a deterrent to many people.

**Comment by BWPanda** [comment]
> I tried Zulip again and still wasn't able to sign in with my GitHub account... I still end up getting redirected to a registration screen every time

@jenlampton Yes, this confused me at first too. You can't just sign in using Github, you have to register an account first (but you can use your GitHub credentials to do so). So proceed with the registration (using GitHub), then you can sign in with GitHub.

That's all from memory, so hope I got it right and that it helps you get access.

**Comment by jenlampton** [comment]
> You can't just sign in using Github

I thought this was a requirement for an alternative to Gitter. If so, Zulip should have been disqualified immediately? (I wonder if the paid version skips the registration step.) I'll give it another try when I have some more time to actually test once I get in.

**Comment by herbdool** [comment]
@jenlampton I think you are getting the _sign in_ and _sign up_ pages mixed up. On https://backdrop.zulipchat.com/register/ you can see:
![Screenshot from 2020-02-04 14-20-06](https://user-images.githubusercontent.com/1071483/73778700-9c68d980-4759-11ea-8f44-463358456a8e.png)

That part works the same way as on Gitter.

So I don't think there's any need to disqualify Zulip.

**Comment by jenlampton** [comment]
The requirement was that people should not need to *create* an account anywhere else, as that would likely stop them from ever participating in chat. I haven't actually walked through that part of the Zulip process (since I thought Zulip was already disqualified) but maybe it's quick painless?

**Comment by herbdool** [comment]
This is similar to how Stackflow works:

![Screenshot from 2020-02-04 14-39-47](https://user-images.githubusercontent.com/1071483/73780317-42b5de80-475c-11ea-8e5f-386c1d35fda3.png)

My guess is that the Gitter process works the same, that it actually creates an account, but that it's just wording it differently and puts the registration part up front rather than the sign in.

I suggest going through the process. It actually is painless.

**Comment by BWPanda** [comment]
@jenlampton Go to https://backdrop.zulipchat.com/register/ and click the 'Sign up with GitHub' button. Follow the steps to authorise Zulip access to your GitHub account, create a display name for yourself, and then you're in.

Here's a screencast :smiley: 
![Peek 2020-02-04 21-45](https://user-images.githubusercontent.com/2385329/73781005-33ed1d00-4798-11ea-8c18-69a6d64087ea.gif)

**Comment by jenlampton** [comment]
> My guess is that the Gitter process works the same, that it actually creates an account

I'm sure an account is created behind the scenes the first time you sign in too, but it feels seamless since it drops you immediately into chat without showing you any of the registration process or asking you any additional information. 

For services like stack overflow that offer to let me "sign up" with another account, I will never do it because I don't ever want those services connected. I expect I'm in the minority though (overly paranoid maybe?).

Thanks @BWPanda! That's way more steps than I was expecting. The "Your almost there" heading is an indicator that they loose a lot of people by that step! I still want to go through it all to see how it feels.

**Comment by BWPanda** [comment]
> That's more steps than I was expecting.

Good news is you only have to do it once :wink:

**Comment by jenlampton** [comment]
It's not me I'm worried about. Everyone has to do it once ;)

**Comment by BWPanda** [comment]
As an experiment (and a bit of fun), I made a list of everyone who posted in Gitter in 2019, ordered by how many posts they made:

```
klonos | 5655
stpaultim | 2434
jenlampton | 2391
BWPanda | 1662
serundeputy | 1477
docwilmot | 825
drupol | 757
herbdool | 715
olafgrabienski | 670
quicksketch | 643
oadaeh | 626
laryn | 549
alanmels | 411
larsdesigns | 367
cellear | 231
deaddred | 194
VasasA | 188
Gormartsen | 179
AlexShapka | 172
bobchristenson | 170
tabroughton | 167
jackaponte | 147
Graham-72 | 135
hosef | 126
mazzech | 126
domaingood | 111
opi | 108
jeffporten_twitter | 99
wesruv | 80
jlfranklin | 73
keiserjb_twitter | 72
Radcliffe | 67
alfabuster | 60
LeeteqXV | 57
findlabnet | 52
indigoxela | 52
dumbgamedev | 51
bradbulger | 50
albanycomputers | 43
arjunk2004 | 40
Egarbeil | 40
ananelson | 32
quinnanya | 31
sbgraphicdesign | 31
SummittDweller | 26
jimmynash | 23
JDSaward | 18
mikemccaffrey | 18
PaulHoza | 18
kelizoliva | 17
Wylbur | 16
frednwright | 15
matthui | 14
wegigciang1 | 14
pvasilion | 11
adamsonh | 10
alexfinnarn | 10
dyrer | 10
AMcKee_gitlab | 8
rfay | 8
tarunkant | 8
adriannolt | 7
deekayen | 6
jonafire_twitter | 6
michaelmcandrew | 6
stephit | 6
twmfc | 6
koffer | 5
korontari | 5
bjoern-st | 4
robertgarrigos | 4
shelane | 4
sternhagel | 4
vstemen | 4
aritomelo | 3
daggerhart | 3
laz0rama | 3
smartey | 3
stanbdos_twitter | 3
floatingleft | 2
JackChin3 | 2
Rados51 | 2
socialtalker_twitter | 2
TopperSaburo | 2
dougouverson | 1
JDSaward_gitlab | 1
jebofponderworthy | 1
kreynen | 1
waybigsky | 1
```

And here's the top 25, coloured based on their support of Zulip:
![image](https://user-images.githubusercontent.com/2385329/73785654-600c9c00-47a0-11ea-9189-9ff5c27df100.png)

I did this to get an idea of the support for Zulip in relation to people's activity in Gitter.

**Comment by BWPanda** [comment]
Ok, so a screenshot's probably not the best way to show that info, especially if it needs updating :smile: 
Here's another attempt (adding @klonos' support for Zulip):

klonos | 5655 :+1: 
stpaultim | 2434 :+1: 
jenlampton | 2391
BWPanda | 1662 :+1: 
serundeputy | 1477 :no_entry: 
docwilmot | 825 :+1: 
drupol | 757
herbdool | 715 :+1: 
olafgrabienski | 670 :+1: 
quicksketch | 643
oadaeh | 626
laryn | 549 :+1: 
alanmels | 411
larsdesigns | 367 :no_entry: 
cellear | 231
deaddred | 194
VasasA | 188
Gormartsen | 179
AlexShapka | 172
bobchristenson | 170
tabroughton | 167
jackaponte | 147 :+1: 
Graham-72 | 135
hosef | 126
mazzech | 126

**Comment by herbdool** [comment]
@jenlampton in my comparison spreadsheet https://ethercalc.org/jthflo2ls7vz it seemed to me that only Gitter and Zulip have this login integration with Github.

When I did it at the time I knew you wanted the github login integration, but I didn't know you had some specific criteria in mind on what was a dealbreaker.

**Comment by stpaultim** [comment]
Easy access to a tool that is frustrating to use is not necessarily a win over `slightly` more difficult access to a tool that is much easier to use. 

I understand the concern that we want to avoid moving to a tool that caters to the already active power users of our community but might discourage new people from joining. 

I don't think that is the case with Zulip. My fear is that Gitter discourages participation and I think that new users that do join Zulip are more likely to hang around and participate. But, I don't have any stats to back that up. 

I'd love more input on that, particularly from the casual chat users in our community. The fact that 22 people signed onto Zulip within a few weeks (at least 6 of whom are not in our top 25 Gitter users) suggests otherwise.

**Comment by jenlampton** [comment]
> I didn't know you had some specific criteria in mind on what was a dealbreaker.

Maybe I didn't? Memory isn't 100% reliable. (esp mine) 

Is there a link to the issue where we first chose Gitter? (just scanned this issue, didn't see one) I think there was a list of actual requirements somewhere...  

> I don't have any stats to back that up.

I'm not sure stats are useful here because we'll never be able get stats on the people we've already lost (because Gitter works like IRC and not like Slack), or will loose (for any reason!). I think a vote makes the most sense :)

**Comment by oadaeh** [comment]
I'm not necessarily in favor of Zulip, but I do not like GItter. Its UX is terrible for me on both Linux and Android. It frustrates me frequently, and so I use it as little as I can. On my desktop and laptop, I use it through a web browser, and the UX is still terrible. I have put up with it, because that's where the Backdrop community hangs out, but I would be willing to move to a better option.

I also do not like the fact that I must log on using the account of some other service. I try to keep logins for different services separate from each other (yes, that means I have a billion accounts).

I am sure over time we will find things about Zulip that are annoying or inconvenient, but for now, it seems to be a good option.

**Comment by jackaponte** [comment]
Here's what I just posted on the PMC issue that Jen created. I think PMC members are _maybe_ supposed to try Zulip for a bit longer than ~30 minutes before we officially vote, but this is where I'm at right now!

---

Huh--I had a different experience, Jen! I was able to use the "Log in with GitHub" button to easily create a new Zulip account and sign in. I was already signed into GitHub, so I don't think I ever had to type anything, just clicked a bunch of times and I was in. To me that barely qualifies as creating a new account--there's not a new/different password or anything like that.

I tried Zulip out for a while. I'll admit that it is very different from anything I've used before, and I found that fairly disorienting, more disorienting than going from Mattermost (open-source Slack) to Gitter. So I'm not totally sold on the thought that Zulip will be more welcoming to new community participants, unless Zulip is a lot like something else that many folks use and I just don't know about?

Zulip kinda feels like Diaspora or Reddit to me: different from other things folks are used to, kinda obscure until you start digging around, kinda feels like it's for Hardcore Techies or something. I think I liked Zulip a little bit more _before_ I actually logged in, when I was just going on Herb's spreadsheet and folks' feedback here in GitHub issues.

All of that said, in the end, I support switching to Zulip for these reasons, most important first:

1. So many active community members and contributors really want something other than Gitter.
2. So many of them have either voiced enthusiasm for Zulip _or_ think it's at least better than Gitter.
3. Signing up and in using my GitHub account felt very easy and hassle-free.
4. The topics functionality in Zulip, while confusing at first, seems really useful to me in certain cases, especially the way the Contrib stream currently has separate topics for different contrib modules. That's awesome!

**Comment by BWPanda** [comment]
Just for posterity, here's an article comparing different open-source Slack alternatives. I believe there's one or two that haven't been mentioned here...

https://itsfoss.com/open-source-slack-alternative/

**Comment by klonos** [comment]
I think that we can close this issue now (see https://github.com/backdrop-ops/backdropcms.org/issues/629#issuecomment-593055498)

**Comment by serundeputy** [comment]
rip; gitter;
