### ISSUE TITLE
How best to use the `backdrop.org` domain?

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/backdropcms.org#594]
**Original post:**
Sorry for a blasphemy of doubting the domain name to which probably the Backdrop community has gotten accustomed since long. I am ok with `backdropcms.org`, but if the main website of the project was `backdrop.com` or `backdrop.org`, then shorter and convenient domain name would be much more appealing. 

I guess the project ended up with the domain name `backdropcms.org`, because both domains were taken. The `backdrop.org` does not open at all and the `backdrop.com` is redirected to https://tradeshowbooth.com/a/pre-launch, and the fact that no active projects are hosted either of domains itches my "why-not?!" type personality. 

I know odds are they'll ask too much if to try to buy out one of the domain names. Taking into account the Backdrop initiative does not have much funding and that on the contrary need donations as disclosed on https://backdropcms.org/contribute, I am just exploring another possibility.

As you probably know, according to https://www.drupal.org/forum/general/news-and-announcements/2006-09-30/dries-buytaert-receives-drupalcom-domain-from the domain Drupal.com once had been generously donated back to Drupal community. So even-though the chances are slim, why not to try to contact their owners and ask them to consider donating in the same manner. 

If none works, what about finding shorter alternatives as for example backdrop.io, etc?

Thank you for your time and consideration!

**Comment by klonos** [comment]
Yeah, I think I recall this being discussed early on, but not sure if we ever filed a GitHub issue for it...

I would not be comfortable with backdrop.com (it would imply that we are a commercial entity - which we are and will never be).

Not sure about .io either; I just have a mental connection to for it with **very** technical things (read: difficult to understand/learn).

I would like us to have backdrop.org if possible, but from memory that was indeed taken some years ago. Also, the cost for it in a couple of registrars I've searched ranges from $10k-$15k! Ouch! 🔥

...even if someone was to purchase it for us and donate it, I would still prefer it if they donated that amount to Backdrop directly, and we channeled that amount towards other tasks (like promotions, or organizing BackdropCons 😄)

**Comment by quicksketch** [comment]
Several years ago we got in touch with the previous owner of backdrop.org by phone. At the time he had .com, .org, and .net and would sell all of them together for $20K. We don't have that kind of money and even if we did, I'm not sure people would appreciate spending that amount on a domain. Sadly, all 3 domains lapsed and were picked up by different squatters, now whom all want $10K for each on separately.

Somehow I doubt "Domain VIP" (the owner of .org) is going to have a heart for open source projects, but you're right it's worth at least reaching out and seeing what they say.

**Comment by alanmels** [comment]
> it's worth at least reaching out and seeing what they say

Yes, please do so referring also drupal.com's case. If it has any chance to effect, then we could ask every member of Backdrop community to support and join such a request to the owner of backdrop.org.

**Comment by jenlampton** [comment]
Both backdrop.org and backdrop.com are registered through GoDaddy, so I have set up domain backorders for each on GoDaddy. I've also emailed myself in the future, to remind me to check on them closer to the expiration dates. 

I do think it would be worthwhile for someone from the PMC to contact all the current domain orders to see if a donation is likely :)

**Comment by alanmels** [comment]
As @BWPanda [suggested](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/backdrop.2Eorg/near/230153663) I'm posting a link to https://www.altagrade.com/blog/altagrade-donates-domain-name-backdroporg-backdrop-community. The domain name has been secured and donated to the Backdrop community.

**Comment by BWPanda** [comment]
I'm unsure about whether we're better off using `backdrop.org` as our canonical domain...

On the one hand, I definitely see the benefit of less typing and the more accurate abbreviation `b.org` (which we often do currently anyway).

On the other hand however, I can see the benefit of having the letters 'cms' in the name, and changing all the (sub)domains and the email address would be a lot of work...

In any case, I think one should redirect to the other.

What do others think?

**Comment by klonos** [comment]
I don't mind either way 🤷 ...for reference, Drupal uses the simplified domain drupal.org.

**Comment by alanmels** [comment]
@BWPanda, is Backdrop only "content management system" or much more? It's the same old debate as they had for Drupal.

https://www.clariontech.com/blog/drupal-8-is-not-a-cms-its-cmf:

> Drupal is a CMF and not just a CMS, it’s a solid enterprise web application framework which uses best of both worlds CMS & WAF to serve a large number of users. Flexible APIs such as actions and triggers, Database API, caching, roles and permissions, Form API, REST API etc. make it an ideal web framework, while continuing to manage the content.

https://www.palantir.net/blog/drupal-not-cms:

> But whatever your approach, whatever your needs, it's important to understand that Drupal is not a CMS. It is a Content Management Framework: A tool for building your own dream CMS, to your specification, for your organization.

https://www.specbee.com/blogs/drupal-is-it-CMS-for-everyone:

**Comment by alanmels** [comment]
Please also see https://www.backdrop.org/issue/207

**Comment by olafgrabienski** [comment]
> I can see the benefit of having the letters 'cms' in the name

I was thinking the same. While the term "Backdrop" doesn't inform you about the kind of product, the addition of "CMS" makes things quite clear. In theory, the same could be said about Drupal or WordPress, but these are already well known.

> is Backdrop only "content management system" or much more?

According to https://backdropcms.org/about it is a CMS:

`About Backdrop CMS`
`Backdrop CMS is a simple, lightweight, and easy-to-use Content Management System for building professional websites.`

I agree, Backdrop can also be used as a framework, but that's not the main focus.

**Comment by quicksketch** [comment]
I think removing "CMS" from the brand name at some point might be valid, but not yet. Apple used to be "Apple Computers", but eventually they reached a critical mass where saying "Computers" was pretty unnecessary (and inaccurate once they were making things other than computers).

Removing "cms" from the domain name is a huge win in my opinion. I would love if people searching for "Backdrop" (without CMS attached) would get us as the first hit in search engines. Right now we're not even on the first page of Google (we're number 13 in my search, just ahead of Wikipedia).

**Comment by stpaultim** [comment]
My biggest concern is the Google implications of not including cms in the name. Search results for Backdrop without CMS are pretty useless, hopefully we can change that. Also, I hope that having backdrop.cms org might help with those kinds of searches. 

Backdrop.org without the "CMS" is much easier for someone new to remember or to intuitively find. In that respect, this is a big improvement.

**Comment by philsward** [comment]
I can't remember how many times I've typed "backdrop.org" only to get the wrong site...

+1 for moving to the new domain name.

It will take time but it will be worth it.

**Comment by jenlampton** [comment]
We can solve the problems with typing and remembering the wrong domain by
setting up a redirect, and we could even do that right away, before the
transfer is done, if needed.

I am ambivalent about removing the cms from the domain name. I personally
prefer it with the cms but also see the advantage of shorter urls. If the
community decides to move to the shorter domain, I'll get on board.

I feel strongly that we should keep CMS in the brand name though, at least
for the foreseeable future. :)

**Comment by philsward** [comment]
> I feel strongly that we should keep CMS in the brand name though, at least for the foreseeable future. :)

Some general thoughts to give perspective, not a CTA by any means.

My view on the "brand" is that CMS isn't used consistently enough to garner it as part of the brand. For example, it is sprinkled throughout the home page instead of used everywhere consistently. And when people mention Backdrop, they refer to it as Backdrop.

I have a rule with brand names: 3 syllables or less.

I have learned that brand names tend to be renamed and recognized by the public, regardless of what the name is and it is of the best interest of the organization to embrace the brand people recognize it by.

I don't have a problem with the structural and legal part of the organization being called BackdropCMS however the frontend is probably going to be best recognized as just Backdrop. An example of this is Coca-Cola. The business entity is Coca-Cola Company, yet their brand is identified as Coke. Hewlett-Packard is know as HP.

So, I would recommend asking: "what is the easiest brand name people will be able to recognize the community by?" And go from there.

**Comment by jenlampton** [comment]
Hm, maybe "brand" isn't the right word for what I meant. I'm still happy to call it Backdrop, but I feel strongly that things like the logo and trademark need to include the CMS. (does that make more sense?)

**Comment by BWPanda** [comment]
I vote for setting up a redirect from backdrop.org to backdropcms.org now, and keeping 'cms' in the canonical name for the time being.

**Comment by alanmels** [comment]
Guys, the whole idea of incurring through additional financial expenses for my company was about giving the domain name to Backdrop community, so it could start using shorter, more convenient and more appealing domain name. Using it just for redirection is kind of undermining the efforts put by my company. Believe me I wouldn't pay so much for the domain name if I knew it would be put just as a redirection point.

**Comment by BWPanda** [comment]
I didn't realise there were strings attached...

> Today, on behalf of my company, AltaGrade I'm happy and proud to announce that the domain name backdrop.org is safely returning to its rightful owner, the Backdrop community, **as an unconditional donation**! The community can start using the domain name any time and **in any way it deems necessary**.

Source: https://www.altagrade.com/blog/altagrade-donates-domain-name-backdroporg-backdrop-community (emphasis mine)

**Comment by docwilmot** [comment]
I really don't believe any entity of our size should simply switch identities suddenly without long thought and planning.

It would be nice to use just Backdrop. But I agree this would require some thinking and planning. I believe from reading above (and I agree) that instead of just letting the domain name sit there while we do this required thinking, that we use it, and redirect to our existing site. Later, after some thought, we can change things.

**Comment by BWPanda** [comment]
Yes, I was merely suggesting that we redirect now while discussions about changing the domain more permanently can continue happening. I wasn't suggesting that we just redirect and then come back to this in a year or so.

**Comment by alanmels** [comment]
@BWPanda, it is indeed unconditional donation, however you should understand decisive people take extra miles in the best interests of other people and it only worth of other people start using, start making some sense of that kind of sacrifices. I hope you understand that it's quite natural for me to expect changes for better with regard to using the domain name.

And then I can't help sharing here about one thing that I didn't like about Backdrop Community - inertness, if it's the right word. Don't take me wrong as I do like EVERYTHING else, but certain sluggishness in Backdrop Community is something that lot's of people notice and walk away. For example, here is just one quote from https://www.backdrop.ru/forum/begite-glupcy (Translate and read the whole thin via Google Translator, it's an interesting discussion).

> I was terribly inspired by Backdrop in 2014-2017, I made websites, ported modules from the Drupal 7, wrote pull requests to the core. Then it turned out that there was no one to check my pull requests, technology was making progress, and the Backdrop community was still discussing how to name a button, Edit or Manage, and called it UX progress. 

It is not about "strings attached", it is about strategical decisions taken in right time that only benefit to the project, it is about giving new inertia, it is about being open to positive changes, to progress. It is up to community what to do, but I'm just sharing my take: it would be real pity if the domain name was not used directly as the whole idea of going through unplanned financial expenses for my company was about exactly that.

**Comment by alanmels** [comment]
And then we are all just expressing our personal stances. I hope nobody incorrectly believes that his/her/their personal opinion is what the community really wants.

**Comment by alanmels** [comment]
Another quote from https://www.backdrop.ru/forum/begite-glupcy, but just note reading it that not only Russian-language kind of sounds harsh as described in numerous Hollywood movies, but also Russian culture is quite direct and not as politically-correct as English culture:

> You see, Sasha, as I already said I also noticed certain inertness of that small group of people who are at the head of the Backdrop project. But they were there from the very beginning, so they have the moral rights to "play the fool." Nevertheless, that's an open source, that's an open and welcoming community and it is quite possible to pull people out of their comfort zone and encourage them to move in a creative direction. 

Sorry to be talking in third person about some people in Backdrop community, but I'm just trying to bring back people like Sasha. And then little bit of self-critisism and giving a though why Backdrop project is not moving forward as dynamically as it potentially could - worth giving some thought. 

Not willing to switch to backdrop.org is a joke, in my personal opinion. Of course, one might easily think that I played the role in obtaining the domain name and as such am interested in putting in use and therefore am pushing here. But then what personal use I could gain from if the domain name would be put in immediate use as the main domain name for the project? None! 

However, I am perfectly aware that so many people searching for Backdrop would end up at the right place at once; I know all the reputable companies, organizations, initiatives, including software projects dream to be on the shortest possible domain name that would concise with their main name, main denomination, main word. Any marketing specialist among you who can explain the value of reputational image and role of the domain names in it? 

There is only one gain for my company, one justification why I invested so much money in getting the domain name - and that is if the Backdrop project will be as successful as it can. So i do hope you, guys, take my reasoning with understanding. And I do hope that I can have a voice just as ordinary member of the community if you can abstract my words from the fact I was the one who brought the domain name.

**Comment by BWPanda** [comment]
@cellear is in marketing, right? What does he think?

**Comment by jackaponte** [comment]
Thank you to everyone who has contributed to this conversation so far, and thank you to @alanmels and AltaGrade for securing the domain name registration for the Backdrop project!

I'd ask everyone to please be patient about potential changes like these. It takes time for a community and the different bodies within it to come to consensus about changes like this; it also takes a significant amount of technical and non-technical planning and careful work to effectively switch the primary domain name for an entire project.

We can certainly start using the new backdrop.org domain name as soon as possible, so it won't go to waste! But as far as I can see, we can only do that in the immediate as a redirect to backdropcms.org for now, in order to allow due time for the community conversation, decision-making process, technical planning and labor needed for any larger changes to occur.

**Comment by alanmels** [comment]
Even-though there are opinions like one of @quicksketch:

> Removing "cms" from the domain name is a huge win in my opinion. I would love if people searching for "Backdrop" (without CMS attached) would get us as the first hit in search engines. Right now we're not even on the first page of Google (we're number 13 in my search, just ahead of Wikipedia).

but then Nate is not in PMC, nor are we - ordinary members of the community. So that leaves us to count what PMC members have expressed so far, and the most of them seem to be willing for the domain name to be redirecting for now.

@jackaponte, thanks for your input. While I do understand about non-technical part of the matter, as a hosting specialist who deals with domain names on daily basis, I know from technical point of view it's matter of seconds to switch the domain name. Of course, it would take time for all the hard-coded paths to `backdropcms.org` (if there are any) to be re-written and for all the occurrences of `backdropcms.org` in the repository to get updates, however that kind of changes can be done any time later and do not represent an obstacle in replacing the domain name.

Anyway, please be informed that per the majority position of PMC members (not the consensus among them, don't confuse, and not per opinion of ordinary members of the community) I have just moved the project on the domain name to https://in.backdrop.org/ and redirected it to https://backdropcms.org.

**Comment by jackaponte** [comment]
> but then Nate is not in PMC, nor are we - ordinary members of the community. So that leaves us to count what PMC members have expressed so far, and the most of them seem to be willing for the domain name to be redirecting for now.

I don't think any PMC members were speaking on behalf of the PMC or meant our comments here to represent any sort of vote or official stance. We are all also community members participating in a community discussion.

Thanks for setting up that redirect, it's great to see https://backdrop.org redirecting to the project homepage!

**Comment by alanmels** [comment]
> I don't think any PMC members were speaking on behalf of the PMC or meant our comments here to represent any sort of vote or official stance. We are all also community members participating in a community discussion.

Good catch, @jackaponte! Just as I should have a right to voice out as on ordinary member without being attached with "strings" to the fact I was the one who brought the domain name in, each of PMC member should be able to speak as an ordinary members. 

But then the question pops up - why we should ignore the opposite opinion of other members of the community? Why then - if all above opinions are expressed as of ordinary members - the position of only one part should be taken into motion? You see, Jack, ordinary member or not, when PMC members voice their opinion they always have more weight, which we all should accept and follow. In other words, by following the wish of some PMC members and redirecting the domain name I've just totally ignored the opposite opinion. And this kind of dilemma could be avoided of PMC members would not take part in public discussions of potentially sensitive matters at all.

Anyway, we - ordinary members of the community - would love to hear the formal decision of PMC on this matter.

**Comment by philsward** [comment]
I can relate to @alanmels urgency on the matter. I agree that the website domain could easily be switched with a redirect from the cms domain over to the non-cms domain with other technical aspects like email etc coming later.

I see the discussion less about determining whether the new domain should be used, and more about how we might want to focus on any hard blockers that would prevent it from being used right away. I'm not on that side of it, so someone who is will be a better person to point out any immediate blockers.

@jenlampton you are right about your comments of the brand. Regarding your views on the logo etc keeping CMS... I'm on the fence. I don't think it will make or break the brand to keep it in graphics or remove it. 

That said, I think the graphical representation of the brand can embrace both ways depending on the target audience or place where it is used. Like my example of Coca-Cola earlier, they brand graphics both ways. If it's done right and consistently, it won't be a problem to use both the "with" and "without" versions.

**Comment by stpaultim** [comment]
> I agree that the website domain could easily be switched with a redirect from the cms domain over to the non-cms domain with other technical aspects like email etc coming later.

From my perspective this is only marginally a technical issue. Even if it is technically easy, as a community we need time to process this change, think through the implications, and make sure that everyone has had a chance to be heard. 

I'm still not 100% convinced that it is technically easy, because of all the technical infrastructure involved in our numerous web properties/sub-domains and all the tools we use to manage our community. We just can't afford to make a hasty change that might bring down some major component of our community infrastructure. I know how easy it is to change the domain name for my own site, I have no idea what complications might occur in changing the domain name for this project. 

Anyone that goes to backdrop.org today is redirected to our site. So this is already a huge improvement and only the first step in the process. 

At this point it's not even clear to me yet, what decisions need to be made and who needs to make them. To the extent that the PMC needs to be involved, we are unlikely to make any major decisions before our next meeting (which should happen in the next 2-3 weeks).  

Some of us are still struggling to resolve the post Backdrop Live tasks that need to be taken care of and trying to catch up on our day jobs/client work. Personally, I can guarantee that any opinion I have today on this topic is likely to change in the next week as I talk to others and better understand what needs to be done. I suspect the same is true of others. 

Some of us are being overly cautious and conservative in our opinions, because we haven't had time to think about this and are nervous about making changes that might have unexpected side effects. As we find time to relax, process, and talk to each other - it may all seem much easier to navigate. Thanks everyone for their patience.

**Comment by olafgrabienski** [comment]
> each of PMC members should be able to speak as an ordinary member.
>
> Why then - if all above opinions are expressed as of ordinary members - the position of only one part always go into motion while others are totally ignored?!

@alanmels I'm one of the PMC members. Indeed I didn't speak on behalf of the PMC, and I don't do in this comment. At the same time, I don't deny that people might perceive a PMC members' statement "somewhat" more important. The same happens probably when @quicksketch or other core commiters speak up, btw.

However, I don't understand your impression that the position of only the PMC part goes into motion while others are ignored. As far as I know, based on this thread, there hasn't been any motion at all. With the exception of the redirect from `backdrop.org` to `backdropcms.org`, but that was done by you.

Regarding some concerns regarding the new domain name, I see them as questions but not as attempts to push a PMC opinion. Also, some PMC members have expressed their opinion pro `backdrop.org`. So I'm not sure what's the real issue here. Maybe a different perception of urgency?

**Comment by alanmels** [comment]
@stpaultim, you can be absolutely assured that if `backdropcms.org` is aliased to `backdrop.org` then nothing will break as all the existing links will be served just as before.

> At the same time, I don't deny that people might perceive a PMC members' statement "somewhat" more important. The same happens probably when @quicksketch or other core commiters speak up, btw.

@olafgrabienski that's why it would be much better if PMC members wouldn't take part in any public discussions that are potentially controversial. Let the people discuss whatever they want, but decide however you do within PMC.

> However, I don't understand your impression that the position of only the PMC part goes into motion while others are ignored. 

Oh, let's not go there - I'm a comparatively new member, however from what I've learned from other people there have been tons of ideas, propositions, suggestions that have been ignored, not properly developed, not fully elaborated just because some PMC members expressed their opinion.

> As far as I know, based on this thread, there hasn't been any motion at all. With the exception of the redirect from `backdrop.org` to `backdropcms.org`, but that was done by you.

Imagine me ignoring how already several PMC members are expressing redirect requests. Would be at least impolite if I didn't do so as they wish. I really don't want to break anyone's feelings, especially those who are in PMC. We - ordinary members - can endure. That's simple and dialectical. 

> So I'm not sure what's the real issue here. Maybe a different perception of urgency?

Not at all as I do understand the processes take time. The real issue is the idea of preserving `backdropcms.org` and using `backdrop.org` as just a redirection point. I didn't spent good chunk of money to buy a "redirection" domain. Be assured unlike some people I know the real value for domain names and I could put this particular domain name for better use. That's my opinion, like it or not, I do also have a right to express my disappointment. But that doesn't mean I'm insisting on anything. I am just expressing my opinion and nobody should get agitated by it. We are all adults, we are all cool.

**Comment by philsward** [comment]
Just to give some perspective on where @alanmels is coming from, he has a LOT more time and I'm sure money involved than any of us realize. He's had time to think through some of the options and scenarios and I'm sure he has had these discussions 100 times in his head already, where this is the first discussion for the rest of us.

Unless technical discussions fall on the PMC, I think the next step is to have those who know the technical implications get together and discuss any potential hard stops. If none, the primary website domain can be switched which is all @alanmels wants right now. The other pieces can follow over time.

Who would be on the list to discuss the technical implications that might break things? Let's get them involved and take their advice instead of guessing what might break. Those folks are in those positions for a reason and we need to follow their direction.

**Comment by kelizoliva** [comment]
These feels like a larger branding conversation that needs to be had; holding a domain hostage and steamrolling other stakeholders does not seem like a constructive approach to this. Can we not redirect the domain at backdropcms.org for now, and then have that conversation? I see no urgency to changing the default domain at this moment time.

**Comment by alanmels** [comment]
@philsward, thank you for your input, but be assured I am far from wanting the domains be switched "right now". We have to PMC to process this issue according to it's own pace. I'm pretty sure they already have lot's of load on their plate. As Tim already said PMC was going to have a formal meeting within the next 2-3 weeks, when they could also consider this matter. No haste and really problem at all with letting PMC to work out.

However, the problem here is, actually, my own misconception that the domain name `backdrop.org` carried crucial importance for the project, and unnecessary efforts from my end based on that misconception to secure it for the community. And that is nobody's, but my own fault. The project has been doing just fine with `backdropcms.org` and can do the same way indefinitely. I do still believe that the project would gain new momentum if it was running on `backdrop.org`, however I can not impose my own believes on anyone. I do apologize for being little more passionate about the domain name. Let's just forget this and move on coding, contributing just like before.

**Comment by alanmels** [comment]
> These feels like a larger branding conversation that needs to be had; holding a domain hostage and steamrolling other stakeholders does not seem like a constructive approach to this. Can we not redirect the domain at backdropcms.org for now, and then have that conversation? I see no urgency to changing the default domain at this moment time.

@kelizoliva, you first read the thread or at least try to open that domain name and then throw wood into the fire.

**Comment by philsward** [comment]
> These feels like a larger branding conversation that needs to be had

I've always thought the brand was "Backdrop". This is news to me that "Backdrop CMS" is viewed as the brand. This whole time I thought CMS was tagged on as an identifier for SEO and identification of what Backdrop is as a product. I figured the domain was chosen because backdrop.org wasn't an option at the time...

So yes, maybe we do need to have a bigger branding conversation.

**Comment by alanmels** [comment]
@keliziliva and some others, you should really stop disseminating lies about `urgency` of this matters. The disconnection here is not about any kind of urgency, but the idea itself of using the domain name `backdrop.org` as just a redirection point, which in my view is just undermining it's real potential.

**Comment by alanmels** [comment]
In my opinion, the branding should also be left at peace as has nothing with the domain name. Nobody has ever suggested to change the brand itself. And people who are mixxing the branding matter here are deliberately taking the subject matter elsewhere from what it should be.

**Comment by BWPanda** [comment]
Random thought: I was just searching for instructions/help on how to use Lando's 'Hyperdrive' software (it's a quick way to get up-and-running with Lando), and in my search something like 80-90% of the results were Star Wars-related, not software-related at all. It was very frustrating. This is a result of Lando's decision to use Star Wars references in their product names (which might have been cute initially but I think is ultimately causing issues with people finding them/information about them).

Now we don't have that exact problem, but we have a similar one - many results in 'Backdrop' searches have nothing to do with software. Now you might say that changing our domain to 'backdrop' and removing 'cms' will help make this better, but I disagree. We'd have to become as popular as WordPress or Drupal before the term 'backdrop' on its own referred to us more than to any other meaning (ideally we'd all love Backdrop to become that popular, but I don't realistically see that happening anytime soon). Instead, I think keeping 'cms' in the domain, and therefore in people's minds as part of the term 'backdrop', will mean less frustrated searches and more people finding what they're looking for.

**Comment by alanmels** [comment]
This is my last entry in this thread. But before going I have a request.

Adding your own misconceptions on top of my own misconception is not helpful at all! Go coding and contributing, and please do not throw any more wood into the fire.

**Comment by kelizoliva** [comment]
@alanmels I hear what you are saying with regard to the domain. Simply donating something to an open source community does not inherently mean your voice becomes more relevant than others' when it comes to said thing. It is great that you are advocating for your opinion, but your approach and somewhat hostile disregard for others' respectfully dissenting opinions comes across unnecessarily divisive, and honestly detracts from the contribution that you made in securing the domain - which in and of itself is appreciated, even if it's current use is not what you personally envisioned.

**Comment by oadaeh** [comment]
I haven't seen this mentioned in the thread (maybe it was alluded to and I missed it, or maybe it is just assumed by everyone), so I'm going to add that the `backdropcms.org` domain should not be let go. It currently has too much market value (even if it is not enough for us) and there are people out there who take advantage of such things that will scoop it up and put other things on it. I have seen it happen more than once with domains of lesser value. (Not to mention the many links pointing to it from other sites.) I believe at some point it would be such that the redirection would go in the other direction (i.e., `backdropcms.org` -> `backdrop.org`) and stay that way for at least quite a long time, if not forever.

**Comment by jenlampton** [comment]
I just wanted to add a quick conclusion to this issue. The PMC has been speaking with SEO and Branding agencies, all who recommend against a complete switch to `backdrop.org` as our primary domain. Even if we were starting over fresh, the experts would still recommend `backdropcms.org` over `backdrop.org`. There are a handful of reasons that `backdropcms.org` is better for the community including:
* A stronger match for people searching for "Backdrop CMS" by name
* Disambiguation between people looking for Backdrop CMS and other types of backdrops
* most importantly: established "domain authority" which would take years to re-establish if we switched to anything else

The PMC does still see a lot of value in the `backdrop.org` domain, and we had been discussing other potential uses or it, but since we are no longer considering moving away from `backdropcms.org`, `backdrop.org` is no longer being donated to the backdrop community.

**Comment by BWPanda** [comment]
> ...since we are no longer considering moving away from backdropcms.org, backdrop.org is no longer being donated to the backdrop community.

Wow 😕

**Comment by alanmels** [comment]
As [I told before](https://github.com/backdrop-ops/backdropcms.org/issues/594#issuecomment-800556969)  I will refrain from further discussions on this, but using the opportunity wanted to thank Jen for the update and to leave a link to my post on https://www.altagrade.com/blog/altagrade-donates-domain-name-backdroporg-backdrop-community#comment-778 

It's all in a lifetime. Some things are meant to never happen. Back to coding.

**Comment by BWPanda** [comment]
I think our own blog post should be updated with the current situation, rather than just unpublished... https://backdropcms.org/news/altagrade-donates-backdrop-dot-org-to-community

**Comment by jenlampton** [comment]
@BWPanda an update is in the works.
