### ISSUE TITLE
System Requirements says PHP 5.3 should it be >= PHP 5.4 since 5.3 is eol?

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/backdropcms.org#62]
The system requirements page: (https://backdropcms.org/requirements) has a requirement of PHP 5.3, but 5.3 is eol (http://php.net/eol.php) and could be a security risk.

Should we state a >= PHP 5.4 requirement?

**Comment by quicksketch** [comment]
The PHP support period is a little misleading at times, because there are a ton of vendors who continue to backport security fixes into the shipped version of PHP in their LTS releases.

For example Ubuntu 12.04 LTS shipped with PHP 5.3, but will be supported [until mid-2017](https://wiki.ubuntu.com/LTS).

RedHat Enterprise Linux 6.x LTS ships with PHP 5.3, but it will be supported until [October 2016](https://access.redhat.com/support/policy/updates/errata).

Debian 6 "Squeeze" LT ships with PHP 5.3, but will be supported until [Feburary 2016](https://www.debian.org/News/2014/20140616)

So even though the PHP core team no longer provides direct support for hand-compiled PHP or provides direct binaries, we'll still be seeing PHP 5.3 for a long time. Currently, PHP 5.3 runs [over 40% of all PHP sites](http://w3techs.com/technologies/details/pl-php/5/all), so in our efforts to lower the requirements for Backdrop as much as possible, it makes sense for us to support it as long as it is widely supported.

**Comment by serundeputy** [comment]
wow; thanks for that super insitefull answer! 
I agree.
closing.
