### ISSUE TITLE
No styling in news RSS feed

### ISSUE THREAD

**Issue by ghost** [backdrop-ops/backdropcms.org#632]
A [recent change](https://github.com/backdrop-ops/backdropcms.org/commit/5824e3c57ffeca379937f8c1832f881041a90722#diff-c7d3efdae3668c1776f12e9182aade71) to the News view has made it so that all HTML tags (save `<a>`) are stripped from the RSS feed body. This means no styling, images, etc. in the RSS feed:

![Peek 2020-01-16 13-36](https://user-images.githubusercontent.com/2385329/72522294-05011c80-3866-11ea-9c38-7d4630b243bf.gif)

I'm not sure why every second item in the RSS feed looks ok, maybe something to do with the dates...?

**Comment by BWPanda** [comment]
The two blog posts added since this issue was created have both appeared in my RSS feed unstyled. Definitely an issue that needs fixing here... Will see if I get a chance to take a look.

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop-ops/backdropcms.org/pull/655

**Comment by jenlampton** [comment]
We need to strip out all the HTML tags that cause the RSS feed to break, so we can't remove the stripping entirely...  I've allowed more tags, including lists and images. 

Can you give this a try?
https://backdropcms.org/news/rss.xml

**Comment by BWPanda** [comment]
That's much better, thanks @jenlampton. I've made a new PR that tweaks your changes a bit to:

- Allow heading tags
- Display the entire (non-trimmed) Body field

The first change is because the styling looks weird if headings are displayed as normal text, and the second because I believe most people who use RSS feeds have an RSS reader where they like to read stuff. So only displaying a teaser and then making them click to view the full post on B.org (instead of their preferred RSS app) seems unnecessary.

**Comment by jenlampton** [comment]
> Display the entire (non-trimmed) Body field

Ah, I had the opposite thought :) I was thinking "why would we put the whole post in here when everyone is just going to go to our site anyway?" 

But since you use one and I don't, I'll defer to you.
