### ISSUE TITLE
Localization server?

### ISSUE THREAD

**Issue by pablo-romero** [backdrop-ops/backdropcms.org#64]
Do you have any plans to add a localization server at backdropcms.org website?

A few Drupal 7 modules may need to be ported first:
- [Plural formula configurator](https://drupal.org/project/l10n_pconfig)
- [Translation Template Extractor](https://drupal.org/project/potx)
- [Localization Server](https://drupal.org/project/l10n_server) and optionally Organic Groups

Some of them don't have a stable 7.x version yet (potx and l10n_server) because localize.drupal.org is still running 6.x, but it's possible to make it work.

**Comment by quicksketch** [comment]
Hi @pablo-romero! Of all d.o services, duplication here seems most unnecessary because the task will be the same between Drupal and Backdrop (or really just about any translated software). However, I don't think our chances are good for sharing the same service. Suggestions we've made about utilizing the drupal.org infrastructure in the past haven't been well-received. It might not hurt to ask, but I think it's likely we'll end up creating an equivalent for Backdrop.

Thanks for opening this issue. We need to start tracking what we're going to do in this area. Let's use this as the canonical issue until we get to the point where we have a dedicated repository (like we do for api.backdropcms.org).

**Comment by olafgrabienski** [comment]
I guess we can close this issue as there is a dedicated localization server repository now (for a while): https://github.com/backdrop-ops/localization

(Can't close by myself, missing permissions.)
