### ISSUE TITLE
Display demo sandbox username & password

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#661]
When https://github.com/backdrop-ops/backdrop-tugboat/pull/7 is merged then sandboxes will be installed automatically and a default admin username and password set. We'll then need to display that information to the user on the 'ready' page.

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop-ops/backdropcms.org/pull/662

**Comment by BWPanda** [comment]
And here's what the page will now look like:

![image](https://user-images.githubusercontent.com/2385329/76677836-9cbb8680-65db-11ea-825a-e0e6e7329813.png)

**Comment by klonos** [comment]
Thanks for working on this @BWPanda 👍 ...feedback:

1. I think that the strings in the template should be passed through `t()`, so that we can translate them in the future.

2. I think that we should be logging the user in automatically. Current workflow:

- click the "Create demo sandbox" button
- click "Visit your site" button
- (choose language) -> "Save and continue" -> installation happens
- (optional) change site name
- type username
- type email
- type password
- click "Save and continue" -> you are logged in, and you can start playing

So 7-8 steps in general

With the new workflow:

- click the "Create demo sandbox" button
- click "Visit your site" button
- type username "admin"
- type password "password"
- click "Log in" -> you are logged in, and you can start playing

So 5 steps, which is better than the current 👍 ...but if we auto-filled the username/password, then it would be 3 steps:

- click the "Create demo sandbox" button
- click "Visit your site" button
- username/password are pre-filled -> click "Log in" -> you are logged in, and you can start playing

I have tried `https://master-r@nd0mStr1ng.tugboat.qa/user/login/?name=admin&pass=password` but user/pass are not auto-filled. It seems that there must be some security feature preventing this by design (hence contrib like https://www.drupal.org/project/auto_login_url and https://www.drupal.org/project/autologin exist).

Anyway, after some research, I came across https://www.drupal.org/forum/support/module-development-and-code-questions/2007-01-29/login-to-drupal-via-url-parameters which suggests adding `$_POST = $_REQUEST;` in `index.php`, which would also allow us to do this:

`https://master-r@nd0mStr1ng.tugboat.qa/admin?name=admin&pass=password&form_id=user-login&op=Log%20in`

I understand that something like the above is insecure, but these are just ephemeral sandboxes - not actual sites. This would eliminate the need to click the "Log in" button, so one less step:

- click the "Create demo sandbox" button
- click "Visit your site" button -> you are logged in, and you can start playing

Now, if we made the following things be `backdrop_set_message()` messages, that are shown post-login:

- "username/password are admin/password" (info message)
- "demo lasts for 1 day" (could be info or warning)
- "emails will not work here - remember your password" (warning)
- "Additional features - go to installer" not required, because we already have the "Add new modules for more functionality" link in the Dashboard 😉

...then we could skip the entire "Your Backdrop demo is ready" step/page, and **get people straight into a Backdrop demo in 1 step** 🎉 🙂

**Comment by klonos** [comment]
...but TBH I am curious as to why pre-filling user/pass in the login form does not work; and also how does the last step in our installer achieve the auto-login.

**Comment by BWPanda** [comment]
> how does the last step in our installer achieve the auto-login

My guess would be: https://github.com/backdrop/backdrop/blob/1.x/core/includes/install.core.inc#L1975

**Comment by BWPanda** [comment]
> I think that we should be logging the user in automatically.

Well I tried: https://github.com/backdrop-ops/backdrop-tugboat/pull/7/files Doesn't work though :disappointed: 

Actually it does, as when I access the site and then manually login, the logs show that being the second time Admin has logged in. So not sure what I'm doing wrong that the initial login doesn't work when accessing the site...

**Comment by klonos** [comment]
> Actually it does, as when I access the site and then manually login, the logs show that being the second time Admin has logged in.

Yup, I have tested with the same results. I believe that what is happening here is this:

1. installer starts and completes successfully
2. as part of the final steps of 1 above, a session is created for user 1 (in the context of the installer)
3. on the tugboat side of things, the link that points to the preview sandbox, has no way to know about the session created for user 1 as part of step 2 (so login is required)

This make me think that the login step during 1 & 2 will not work (hence should be removed).

Now, if there was a way to pass session ID (or a login token) to the link generated by tugboat, then that would work.

**Comment by klonos** [comment]
...tugboat supports defining env variables (https://docs.tugboat.qa/setting-up-services/how-to-set-up-services/custom-environment-variables), but I'm not sure how these could be used to achieve what we're after 🤷‍♂ ...could we dump an access token into a variable as part of the preview installation? ...if we could do that, then perhaps that variable can somehow be exposed (https://docs.tugboat.qa/reference/environment-variables/#exposed-service-variables).

**Comment by BWPanda** [comment]
I've updated the PR to create and print (to the terminal) a one-time login link instead. It works, if you have access to Tugboat's terminal and copy/paste it. Now just need to work out how to send that URL to B.org to display to the user...

**Comment by BWPanda** [comment]
Documenting here a conversation from Tugboat's Slack:

> **BWPanda:**
In my Tugboat config file, it runs a script as part of the update command/step. In that script, I generate a unique URL that I need to send to the user so they can access the site (and be automatically logged in). What's the best way to do this?
So the URL is generated in a PHP script in the .tugboat directory in the repo being built. That needs to get sent to the user who's provisioning this repo via a site which uses the Tugboat API. So the URL needs to go from the PHP script in the provisioned repo to the user, likely via the Tugboat API.
I looked through the API but couldn't see anything obvious for this. What did I miss?

> **Jonathan Daggerhart:**
It sounds like something I have setup. I have a script that updates a trello ticket with a link the the tugboat instance, and some other things. It does this by using the trello api.
In your case, maybe you can have tugboat send an email? or add a comment to the github pr?

> **Jonathan Daggerhart:**
In another setup I worked on I had tugboat deliver messages back to a site using curl/wget.
I created a simple module on the provisioner site that could accept messages from tugboat, then during the tugboat build process, used curl to send the messages about the status of the build.

That last suggestion was given a thumbs-up by Adam Bergstein, and I think it might be the solution here for us...

**Comment by BWPanda** [comment]
Another solution given on Slack was to print the login URL in the terminal/log (which I'm already doing for testing), then get the log via the Tugboat API. I'm currently working on this solution.

**Comment by BWPanda** [comment]
Due to the tricky nature of testing this (by needing Tugboat, plus a PR for the backdrop-tugboat repo), I've decided to merge https://github.com/backdrop-ops/backdropcms.org/pull/662 and perform future testing live. But from my local testing it seems to all be working nicely now.

**Comment by quicksketch** [comment]
This is working great! Previews do take a bit longer to generate now. It used to be about 10 seconds, now it's more like 50 seconds. I love that the "Visit your Site" button now automatically logs you in!

**Comment by stpaultim** [comment]
I noticed the slowdown as well, but of course the auto login compensates for that. This is really nice.

**Comment by BWPanda** [comment]
The slowdown is because: it used to 'clone' the base preview, so it was really quick. Now however, in order to run the code for generating the login URL, etc., it has to run the build steps which means building the site from the base preview. So it takes longer to do that. But its still much quicker than not having a base preview to build from (e.g. then it'd have to setup the full environment each time).
