### ISSUE TITLE
LBRY/Odysee for Weekly Video Meetings

### ISSUE THREAD

**Issue by ghost** [backdrop-ops/backdropcms.org#671]
We currently record meeting videos and upload them to YouTube. Does anyone have any experience with LBRY? https://lbry.com/ If so, what are your thoughts on uploading our meeting videos there, either in addition to, or instead of to, YouTube?

**Comment by quicksketch** [comment]
I haven't seen LBRY before. But a quick check through their site and functionality it seems pretty promising.

One of the key things for our weekly meetings is reducing the amount of effort it takes to publish them. With Zoom (and previously Hangouts) the key feature we want is the ability to automatically publish the videos without needing to download and then upload them again. I think a lot of people also appreciate the live streaming functionality so they can watch the meetings as they happen even if they don't join directly. Can LBRY provide similar features?

**Comment by BWPanda** [comment]
> Can LBRY provide similar features?

Probably not...

**Comment by stpaultim** [comment]
Thanks for sharing, I spend some time yesterday reviewing library. Even uploaded one of my own videos. It's interesting, but it's also not clear to me that it solves our problems...

**Comment by BWPanda** [comment]
Here's a write-up that just came out by It's FOSS about LBRY: https://itsfoss.com/lbry/

**Comment by BWPanda** [comment]
Seems @stpaultim setup an official BackdropCMS account...? https://lbry.tv/@BackdropCMS

**Comment by BWPanda** [comment]
@quicksketch @stpaultim Since LBRY *does* support auto-posting from YT, I don't see a reason why we shouldn't do that. I'm willing to set it up if you like, but I think I'd need access to the Backdrop email address, YT account, etc. Hit me up privately on Zulip if you'd like me to do that.

**Comment by stpaultim** [comment]
I did upload a video. I don't recall that it was my intention to set up a Backdrop CMS account (that would have been presumptious at the time). I was just experimenting. But, I found the process very confusing and it's possible that I did take that route.

I still don't understand how LBRY.tv works.

**Comment by BWPanda** [comment]
@stpaultim No worries, I'm still getting my head around how parts of LBRY work, especially the naming system: https://lbry.com/faq/naming

By 'official account' I just meant that you setup the `BackdropCMS` namespace: https://lbry.tv/@BackdropCMS However from what I understand, anyone can setup a channel with that name, and the one with the most support/credits becomes the official one (but I'm still struggling to understand the whole naming thing).

So I'm not quite sure of the best way forward should the PMC decide to add our videos to LBRY in addition to YouTube... I think we have two main options:

1. Setup an account/login using the Backdrop email address and take over the `BackdropCMS` namespace claim from @stpaultim.
2. Use @stpaultim's account (or mine if he doesn't want to manage it going forward) and setup the BackdropCMS YouTube account to pull in videos to that login.

Regarding credits, you need them to upload videos, in that you assign credits to a URL/namespace to 'reserve' it. The default amount is 0.1 BTC, but since you don't get many credits to start with, I'd suggest verifying your account to allow rewards which means you'll get credits for watching videos, following people, etc. Then you'll have enough to upload more videos, etc. You may also get credits from users watching your videos, but this is another area I'm not familiar with. So this may mean it'd be better to setup the account under a login that's actively used so as to gain more credits going forward.

**Comment by BWPanda** [comment]
Closing for now due to lack of interest.

**Comment by BWPanda** [comment]
Re-opening this as I'm now using Odysee (aka LBRY) regularly and would love to see Backdrop videos on there. I even intend to make more of my own to put on there in future. I've initiated the sync from YouTube and it'll take a while, so once it's done I'll post back here with the link to Backdrop's Odysee channel.

**Comment by BWPanda** [comment]
Here it is: https://odysee.com/@BackdropCMS

This should remain synced with the YT channel automatically.

Closing this issue as done now.

**Comment by BWPanda** [comment]
Actually, sorry, I'll keep this open a bit longer while I update various places to link to our Odysee channel.

**Comment by BWPanda** [comment]
Ok, done now (sorry for the noise). I've added links to our Odysee channel in the main page content and the Resources block here: https://backdropcms.org/support/resources
