### ISSUE TITLE
Releases history XML feed missing "terms"

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#72]
See feed for views on Drupal:

```
<project xmlns:dc="http://purl.org/dc/elements/1.1/">
  <title>Views</title>
  ...
  <terms>
    <term>
      <name>Projects</name>
      <value>Modules</value>
    </term>
    <term>
      <name>Maintenance status</name>
      <value>Seeking co-maintainer(s)</value>
    </term>
    <term>
      <name>Development status</name>
      <value>Under active development</value>
    </term>
  </terms>
  <releases>
```

Backdrop feeds dont have "terms" node.
https://updates.backdropcms.org/release-history/backup_migrate/1.x

**Comment by quicksketch** [comment]
Hi @docwilmot, I had changed this functionality because "terms" were only used for exactly one thing in update.module: security updates. Rather than loop through terms and looking for the special term "Security update" (an exact string), I made a stand-alone XML tag for `<security_update>true</security_update>`. However, update.module hasn't been updated to check for this flag yet, so for compatibility `<terms>` are still created if (and only if) it's a security update.

By avoiding the taxonomy vocabulary for security updates, sites which set up project module (dev sites particularly) don't have to have a specially named term to get security updates working. Instead it's just a checkbox if the release contains security fixes.

**Comment by docwilmot** [comment]
Understood. Should we create an (META?) issue to fix update module then? I did a PR recently to add layout support; is there anything else thats missing? (Obviously I am into update module these days since project browser depends on it.) :smile:

**Comment by quicksketch** [comment]
> Should we create an (META?) issue to fix update module then?

Yes please, that'd be great. I don't think it needs to be a meta unless you're encountering a lot of issues with update.module.

**Comment by docwilmot** [comment]
We seem to be doing fine without this.
