### ISSUE TITLE
Fix page title on home page

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#761]
BackdropCMS.org's page title (shown in the browser tab) seems to be missing something at the end...

> Backdrop CMS |

It should either have something after the `|`, or the `|` should be removed.

![image](https://user-images.githubusercontent.com/2385329/107455743-68619900-6ba3-11eb-8149-b30eeaa88878.png)

**Comment by philsward** [comment]
Just noticed this as well and was going to open an issue.

Instead of hashing out every permutation of what it "could" be, let's get a few ideas rolling for a title and get it added ASAP for SEO purposes. It can always be tweaked later.

What I add to start off with:

**Backdrop | PHP Free Open Source CMS For Data Focused Website Needs**

Keep in mind that any suggestions need to be checked against a 70 char limit.

Ping @jenlampton @stpaultim @klonos Not sure who has access to make these changes?

**Comment by BWPanda** [comment]
I was more pointing out the fact that there's a separator but nothing after it. In other words, whatever text was already decided to be there isn't, so its a bug.

**Comment by philsward** [comment]
@BWPanda definitely a bug that there is no SEO title. It was brought up recently that the website is ranked really low. This is a major ranking factor on why it's ranking low!

Do a search on "free open source cms PHP" and backdrop is nowhere to be found. This needs fixed.

**Comment by jenlampton** [comment]
I believe @mattias was working on setting up metatag module. We should check with him before we change too much, but I have updated the title + description tags for the home page to get that part going at least.

**Comment by jenlampton** [comment]
The current page title for the b.org home page is `<title>Backdrop CMS | Free Open Source CMS built in PHP</title>`
