### ISSUE TITLE
Better, less US-centric handling of time changes and scheduled meetings

### ISSUE THREAD

**Issue by jackaponte** [backdrop-ops/backdropcms.org#779]
As discussed [in Zulip yesterday,](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Weekly.20Meetings/near/230926651) folks outside of the US missed this week's meetings. We in the US kept the meetings at their usual time on our clocks which we also turned back this past Sunday for Daylight Savings Time (DST), which caused the meetings to start an hour earlier for people in non-US timezones. From the Zulip conversation it sounds like more time changes are coming soon for other countries (e.g. Australia).

How can we better deal with planning and announcing our meetings to avoid this sort of disruption when clocks change in the US and elsewhere?

At the very least it seems like we should make sure that if we're scheduling the meetings according to US clocks we announce the start and end of DST ahead of time, so folks outside the US know the meetings will be at a different time than usual for them.

But maybe there are even better, less US-centric ways of dealing with this?

**Comment by BWPanda** [comment]
Most people know when their own timezone changes, and can adjust meetings, etc. accordingly. That's not the issue (or if it is then it's their own fault). I think the real issue here is that the meeting times are based on a US timezone that non-US users don't (and shouldn't have to) keep track of.

So, I suggest we base meeting times on UTC/GMT time instead (since that doesn't change throughout the year, and is a good, international standard (since we're trying to be more international-friendly)). This will mean that non-US users only need to worry about meeting times changing when their own timezones changes, and US users will just have to adjust an hour back or forward twice a year like the rest of us from now on.

I suggest 8pm UTC/GMT for the first (outreach/UX/design) meeting, and 9pm UTC/GMT for the second (dev) meeting. All year 'round.

**Comment by stpaultim** [comment]
@BWPanda - that is a great suggestion. It would also be nice if we had an automated way to send out a notification of meetings one hour in advance, so that regardless of your time zone or country (and without any of us having to remember), everyone will get notification. 

Just to be clear, this means that for anyone in a location with daylight savings, including those of us in the USA. The time of the meetings WILL change twice a year. The good news is that it will change at maximum by one hour. Currently, Peter and some other people in Southern hemisphere are experiencing a two hour shift.

**Comment by BWPanda** [comment]
@stpaultim Exactly. Currently in Australia the meetings times change 4 times per year (once when US change clocks, again a few weeks later when we change clocks, then repeat that in 6 months time but the other direction). And as you said, they end up ultimately changing by 2 hours here.

So my suggestion kind of smoothes all this out so that the US shares some of the changes and some of the hours difference (everyone only changes twice a year, and only by an hour).

And those lucky enough to live in non-DST areas don't change at all 🙂

**Comment by BWPanda** [comment]
I have added this issue as a general discussion point for the end of the next developer meeting. Since I can't be there (because, you know, timezone issues), can @stpaultim bring it up?

**Comment by stpaultim** [comment]
> I have added this issue as a general discussion point for the end of the next developer meeting. Since I can't be there (because, you know, timezone issues), can @stpaultim bring it up?

Yes, I can do that.

**Comment by jackaponte** [comment]
> I suggest 8pm UTC/GMT for the first (outreach/UX/design) meeting, and 9pm UTC/GMT for the second (dev) meeting. All year 'round.

I like that suggestion, @BWPanda!

Translating this to my own timezone helped me understand it better. I'm in the Pacific time zone; during Daylight Savings Time the first meeting would be at 1pm PT and the second at 2pm PT. During standard (non-DST) time, the first meeting would be at 12pm PT and the second at 1pm PT. That seems more than fair and easy to manage, especially if we find good ways to remind everyone about the changes.

**Comment by BWPanda** [comment]
> This may be something that Dragonbot can handle (which will require that I [...] ideally, get the code into a repo where someone else can make it).

Please do. There are a few reasons now why dragonbot should be publicly accessible.

**Comment by BWPanda** [comment]
> Translating this to my own timezone helped me understand it better. [...] especially if we find good ways to remind everyone about the changes.

I made some links we can use! Try them out:

['Design' meeting in your timezone](https://www.starts-at.com/event/2552209954)
['Outreach' meeting in your timezone](https://www.starts-at.com/event/7123817766)
['Developer' meeting in your timezone](https://www.starts-at.com/event/4695504400)

**Comment by stpaultim** [comment]
@BWPanda - We discussed this in the dev meeting today and the consensus is to go ahead and change the official meeting time to your suggestion (effective April 8th). We just want folks to have time to adjust to the new schedule. 

New meeting time will be 8pm UTC/GMT for the first (outreach/UX/design) meeting, and 9pm UTC/GMT for the second (dev) meeting. All year 'round.

This will mean an effective change of moving the meeting 1 hour later for MOST participants in the US for the summer (starting April 8th). For US participants it will return to the old time in the fall.

**Comment by BWPanda** [comment]
In today's dev meeting this issue was discussed (thank you!) and there were questions about exactly what times we should make the meetings going forward (i.e. if the above proposed times are indeed the best option). For simplicity, let's just focus on the weekly dev meeting, and just assume the other fortnightly meetings start an hour before that...

I feel like this particular issue is about smoothing out the clock changes across all timezones, so that no one timezone is more (dis)advantaged over another. Any discussions about moving the meeting times to a whole other time of day (or day of the week) is a different issue altogether. Therefore I feel that the changes we make in *this* issue should be as close as possible to the current meeting times.

So what are the current meetings times? If we consider two dates (in January and July respectively), then meetings times are **currently** as follows:
- USA (West coast): 1pm/1pm
- Europe (Central): 10pm/10pm
- Australia (East coast): 8am/6am

By changing meetings times to be based on UTC instead, it'll mean one of the times for each location will change. The question is, do we change it backwards or forwards...?

Here are the two options:

**UTC: 8pm**
- USA (West coast): 12pm/1pm
- Europe (Central): 9pm/10pm
- Australia (East coast): 7am/6am

**UTC: 9pm**
- USA (West coast): 1pm/2pm
- Europe (Central): 10pm/11pm
- Australia (East coast): 8am/7am

**Comment by BWPanda** [comment]
Ah, I see @stpaultim already posted...

**Comment by BWPanda** [comment]
Changing the meetings on April 8th means the change notice can go out in the next newsletter too 🙂

**Comment by BWPanda** [comment]
I have updated the above links to start on or after the 8th of April. And I have setup an account at that website so we can make any future changes to those links easily (login details in 1Password).

**Comment by BWPanda** [comment]
Since the next meetings are at the new times, I've updated the two pages on B.org that list meeting times. I think we can close this now.
