### ISSUE TITLE
Project release date vs post date in project views on backdropcms.org

### ISSUE THREAD

**Issue by jackaponte** [backdrop-ops/backdropcms.org#793]
On April 22 I created a [new release of the Webform CiviCRM module in GitHub.](https://github.com/backdrop-contrib/webform_civicrm/releases/tag/1.x-5.5.0) That automatically triggered the creation of a new release on the backdropcms.org Backdrop site, as seen on https://backdropcms.org/project/webform_civicrm and https://backdropcms.org/node/1397/releases.

But every time I checked the Modules page (Project listings page view) at https://backdropcms.org/modules I didn't see Webform CiviCRM appear towards the top of the view. Over the course of a few days I saw other module releases from that day and later appear towards the top of the Modules view. I realized that in that view, Webform CiviCRM Version: 1.x-5.5.0 still showed a "Released" date of Jun 19th, 2017, which is when the first version of the module was released, not when version 1.x-5.5.0 was released.

The only way I found to get the right date reflected on these page views this was to manually edit the "authored on" date on the project node itself, but it seems like that shouldn't be necessary if the intention here is to display and sort by the most recent release date.

For another example, see the [Forum Access module](https://backdropcms.org/project/forum_access) which had a May 3 2021 release, but on the [Modules view](https://backdropcms.org/modules?s=forum) the 1.x-1.4.2 release date is shown as Dec 6th, 2019.

**Comment by jackaponte** [comment]
I'd try to fix the view myself but figure I should ask first! Also the views are fairly complex so I don't want to go mucking about with it on the live site. What's the editorial process for editing views and other configuration on backdropcms.org, anyway?

**Comment by bugfolder** [comment]
There are a few places where the release date doesn't match the release number. For example, see Ubercart, whose releases are all here:

https://backdropcms.org/node/1470/releases

The most recent release is 1.x-3.13.0-rc2, release Oct 7th, 2020.

Now, on the Modules search page:

https://backdropcms.org/modules/?s=Ubercart

The version is correct, but the release date is wrong (same problem that @jackaponte pointed out above).

On the project page:

https://backdropcms.org/project/ubercart

The only release shown in the main content region is an older release, while the more recent and recommended version is only listed under "Other releases" in the right sidebar.

(Incidentally, if we're going to list the recommended version and "See all versions", then this sidebar chunk shouldn't be called "Other releases", and, really, doesn't need a heading at all, since its contents are self-explanatory.)

A PR addressing all of these will be forthcoming shortly.

> What's the editorial process for editing views and other configuration on backdropcms.org, anyway?

[Described here under "Contributing".](https://github.com/backdrop-ops/backdropcms.org)

**Comment by klonos** [comment]
Thanks for working on this 🙏🏼 ...code looks good overall.

I confirm that the release date for the most recent (recommended) version is now the proper one (reflecting the respective release date in GitHub) 👍🏼 

The project node pages now have the following strings:
- "Recommended releases"
- "Other releases"
- "Recommended version"

...can we please pick one and stick with it? (i.e. either "release" or "version")

**Comment by bugfolder** [comment]
> ...can we please pick one and stick with it? (i.e. either "release" or "version")

Makes sense to me (I'd assumed the difference was there for a reason, so left that wording as-is). A question though: is it the intention that there is only ever a single "Recommended release" (in which case "Recommended release"), or are there cases where there are multiple recommended releases (e.g., to support older versions of libraries)?

**Comment by bugfolder** [comment]
> ...can we please pick one and stick with it? (i.e. either "release" or "version")

Just thinking about this further...

1. Is "Recommended version" and "Release date" in the sidebar (outlined in red) even necessary?That information is just to the left in the Recommended releases block. Seems superfluous now in the sidebar.
2. Speaking of which, "Post date" for the download should probably be changed to "Released".
![Recommended version](https://user-images.githubusercontent.com/29214084/122649382-6758ef00-d0e2-11eb-8a7a-8d0e25f8a76c.jpg)

**Comment by bugfolder** [comment]
Haven't seen further commentary, but I have made several further changes to the PR in the `project_release_download_table` View that, I think, improves the UX on any project page:

On the main part of the screen:

* Remove the word "Download" from the download link text. It's clear from the column label "Download" that this is what the link does, and the word takes up unnecessary space on small screens.
* Added release dates to this table so that we get to see release dates for all supported versions (no release date was visible for "Other versions" previously).
* Remove column heading of "Links" for the Notes link. It's clear that it's a link, doesn't need a heading.
* Added CSS for the download tables so that they format better on small screens.
* Added a download arrows on Other releases, to match the download arrow on Recommended releases.

In the sidebar:

Remove "Recommended version" and "Released", because they're now redundant.

Here's before and after for comparison.

Before:

![before](https://user-images.githubusercontent.com/29214084/123470985-fdd95480-d5a9-11eb-9737-0bfd5bea5227.jpg)

After:

![after](https://user-images.githubusercontent.com/29214084/123470997-029e0880-d5aa-11eb-925e-700b2fc6d7de.jpg)

**Comment by quicksketch** [comment]
I agree, the new version looks a lot better and is less redundant. We could use a lot of other design help on these pages (e.g. making the recommended release green vs yellow for other releases), but major reworking can be a separate issue. The PR helps a lot with content problems without adjusting the design too much.

**Comment by stpaultim** [comment]
Yes, I think this looks good and is really helpful.

**Comment by bugfolder** [comment]
I added one more small change to the PR: making Downloads and Active Installs each inline. Improves readability, and also matches the way they are displayed on the search results page. Side benefit is that the "See all versions" link doesn't look so lonely now.
![example](https://user-images.githubusercontent.com/29214084/124398749-370d7500-dccc-11eb-96ac-90c5938a6f40.jpg)
