### ISSUE TITLE
CiviCRM: How to use only a single name field? (instead of first/last or first/middle/last)

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#843]
When we created user profiles on the Backdrop site, we deliberately decided not to use the Eurocentric First name / Last name combination, knowing that this pattern only works for a fraction of people on the planet, and wanting our community to be inclusive. 

Unfortunately, it appears that CiviCRM, like so much other software, does not account for people who's names don't this pattern. 

Here's a list of possible solutions we could approach:
* Use only the `Last name` field in civi, re-label it as `Full name`
* Write a new Civi plugin to allow the use of a single `Full Name` field
* Resign ourselves to making the Backdrop community a less inclusive place (just like the rest of the internet has already done)

I found this post in ths civi forum, which might be useful:
[How to work with names that don't fit first, last](https://civicrm.stackexchange.com/questions/6875/how-to-work-with-names-that-dont-fit-first-last?newreg=e937645d77c0430994dc76e0b7b588c3)

**Comment by jackaponte** [comment]
@jenlampton and @bugfolder at today's meeting we landed upon a good plan for dealing with this; could one of you document that plan here?

**Comment by bugfolder** [comment]
We can simply put the full name in CiviCRM's "Last Name" field and leave the other fields blank. Then one can search for a contact by name (based on any part of the name), and in search listings, contacts will show up with the full name. (I've done this with the contacts on beta.backdropcms.org.)

The only (potential) drawback is that the default sort (alphabetic) will be based on the full name, rather than the family name (as we could have with split fields); but that's going to be inherent in keeping the full name atomic.

**Comment by jackaponte** [comment]
Thanks for documenting that here @bugfolder!

Does this need any further discussion, documentation, or next steps? Or can this issue be closed with that as the planned solution?

**Comment by bugfolder** [comment]
I moved it into the "Done" column on https://github.com/backdrop-ops/backdropcms.org/projects/3.

BTW, thanks, @jackaponte, for linking to that. It looks like a great tool for keeping track of all these different issues.

**Comment by jackaponte** [comment]
Thanks @bugfolder! And always happy to share project management tips and tricks. :)
