### ISSUE TITLE
Create Tugboat instance for 1.x branch

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/backdropcms.org#908]
I've heard some requests recently for a way people can test the preview release and/or latest features in general. While I don't think it's worth setting something up just for preview releases (since they're only around for ~2 weeks, three times a year), I think it might be worth giving people the ability to test the latest features/bug fixes by trying the 1.x branch (all year 'round).

To that end, I had the idea to setup a new Tugboat instance based on the 1.x branch. But instead of people being able to create their own individual previews (because that'd require asking Tugboat for even more free quota), I thought just one sandbox would be fine if we add in an automated hourly reset. Not sure if/how that'd be possible, but wanted to get some feedback on the idea first.

@klonos and @stpaultim have brought up the suggestion in recent meetings (which is what prompted my idea), so particularly interested in their feedback. Also, I added this to the B.org repo's issue queue since if we set this up I think we should add a (small) link on the Demo page for it (which'd go to a new page giving the login details and explaining the hourly reset and fact that this version may contain bugs).

**Comment by stpaultim** [comment]
I'm interested in the idea and in experimenting. I think it's better to try something and improve upon it rather than waiting to get it right the first time. 

An auto reset ever hour runs the risk of resetting while folks are using it. But, there might be ways of getting around that. 

Can we get any statistics on our Tugboat Demos?

It might be nice to know if anyone used them except @klonos and myself? ;-)
If we launch something like this, it would be nice to know if anyone is using it.

**Comment by BWPanda** [comment]
Here's a PR that adds a new button to the demo page: https://github.com/backdrop-ops/backdropcms.org/pull/910

The button takes you to this (currently unpublished) page: https://backdropcms.org/demo/dev
It has the login details for the dev preview site.

It should refresh automatically every day at 6am UTC. This not only reverts peoples changes and resets the site back to default (to avoid build up of dummy content, cruft, etc.), but also pulls in the latest changes from the `1.x` branch.

I also disabled the installation of the PHP 'zip' module, which is required to install packages using the UI installer. I did this to prevent people installing contrib modules, themes, etc., since I figure this preview is just about viewing/testing core changes. If people want to test contrib stuff, they can use the regular demo sandboxes (which are specific to them).

Happy for feedback on any of the above though.

**Comment by BWPanda** [comment]
And here's what it looks like:

![image](https://user-images.githubusercontent.com/2385329/169288634-5efee6ae-a4f7-4cf9-a09e-00f1e3dc0e1e.png)

![image](https://user-images.githubusercontent.com/2385329/169288738-95a5cd4a-0cdc-4e8f-afc3-2016b8121d17.png)

**Comment by BWPanda** [comment]
@stpaultim As for your question re. statistics for the current Tugboat sandboxes, if you have access you can go to https://backdropcms.org/admin/reports/tugboat and see a list of all the demo sandboxes that currently exist. Since each sandbox only lasts 24 hours, viewing that page at the same time each day will start to give you an idea of how many sandboxes are created. Not sure if there's an easier way than that...

**Comment by jenlampton** [comment]
First of all, thank you @BWPanda for working on this, it's something we've been talking about doing for a while and it's so great to see it happen :)

One thing brought up in today's weekly meeting was to move the link to someplace where only the people interested in testing future versions of core can find it. We don't want people who are first evaluating backdrop to click the link, potentially discovering critical issues, or incomplete features that are currently still under development.

I recommended adding it to the "More ways to try" page, with brief explanation of what it means to be a -dev version so that expectations are set accordingly. 

> Here's a PR that adds a new button to the demo page: https://github.com/backdrop-ops/backdropcms.org/pull/910

Items are added to the "more ways to try" page by creating a new "platform" node, so nothing needs to be included in this PR to add the link to that page, but we do need to remove the button from the demo page.

**Comment by BWPanda** [comment]
Good idea. Here's the draft Platform node: https://backdropcms.org/platform/1x-dev-preview

![image](https://user-images.githubusercontent.com/2385329/169427572-f771e7b5-88b3-428a-9185-dfa521ade529.png)

Wasn't sure if we wanted the login details directly on this page, or if the button should link off to a page that has the login details... Went with the former for now, but kept the old page (just changed the URL) in case we want to do that instead: https://backdropcms.org/try-backdrop/dev

Will close PR since that's no longer needed.

**Comment by jenlampton** [comment]
> Wasn't sure if we wanted the login details directly on this page, or if the button should link off to a page that has the login details... 

My preference is to include the information in the link. Having "Password:" on any page is so easy to scrape it seems ripe for bots. Smart bots could still find it in the link, of course, but removing the low-hanging bait may at least keep the dumber ones at bay :)

**Comment by BWPanda** [comment]
Thanks for the feedback @jenlampton. Since there's no PR anymore, I've gone ahead and published the new content:
- https://backdropcms.org/try-backdrop
- https://backdropcms.org/try-backdrop/dev

We can leave this issue open for a bit if there are any suggested wording changes, otherwise this issue can be closed.
