### ISSUE TITLE
Gather project usage data for specific features and display them in a useful way on backdropcms.org

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#99]
We'd like to collect more than just the Backdrop version people are running. These things will be helpful for our decision making process, since we need to know what applies to "the majority" of Backdrop sites. If we ever want to remove features from core, it would be great to have some data backing up our theories that feature isn't used much.

Below are a list of the new features we'd like tracked via project usage:
- which core modules are enabled
- are clean URLs enabled?
- which core layouts are in use?
- which core module field types are in use?
- which contrib modules (not projects) are in use?
- which color module color palettes in use?
- how many roles are in use (and their names?)
- how many sites are using revisions?

Is there anything else we may need metrics on?

**Comment by klonos** [comment]
For reference to related issues on d.org:

[Establish heuristics for core feature evaluation](https://www.drupal.org/node/1273344)
[Drupal.org should collect stats on enabled sub-modules and core modules](https://www.drupal.org/node/1036780)
[Provide means for module maintainers to collect heuristics on certain settings of their modules.](https://www.drupal.org/node/1439316)
[Display stats on enabled components (e.g. modules included in a project)](https://www.drupal.org/node/1627676)
[Collect stats on enabled sub-modules, not just projects](https://www.drupal.org/node/1274766)

From the last issue above:

> Patches have been committed to D7 and D8 to enable us to collect more information about installed contrib modules, sub modules, and core modules. But it seems we still need to loop back and get Drupal.org to listen for this info, record it, and ultimately display it somewhere useful.

Since we "inherited" from D7 and we do keep parity with most features in D8, does that mean that this is implemented in Backdrop too and all we need to do is "listen"?

**Comment by Gormartsen** [comment]
Is there a way to see a backdrop usage stats ?

**Comment by stpaultim** [comment]
@jenlampton - Is this covered by Telemetry? Maybe this issue is complete?

**Comment by jenlampton** [comment]
Yes. This issue is not complete, but there are various issues in core that will solve this problem once all completed, so we can close this as a duplicate.
